### ISSUE TITLE
Error: unable to build kubernetes objects from release manifest: [unable to recognize "": no matches for kind "Certificate" in version "cert-manager.io/v1alpha2", unable to recognize "": no matches for kind "Issuer" in version "cert-manager.io/v1alpha2"]

### ISSUE THREAD

**Issue by sTb1337** [SAP/sap-btp-service-operator#101]
Error when installing via helm:

Chart.yaml:
 - name: sap-btp-operator
    version: "0.1.17"
    repository: "https://sap.github.io/sap-btp-service-operator"

"Error: unable to build kubernetes objects from release manifest: [unable to recognize "": no matches for kind "Certificate" in version "cert-manager.io/v1alpha2", unable to recognize "": no matches for kind "Issuer" in version "cert-manager.io/v1alpha2"]"

From https://github.com/jetstack/cert-manager/releases/tag/v1.6.0:

Breaking Changes (You MUST read this before you upgrade!)
⚠️ Following their deprecation in version 1.5, the cert-manager APIVersions v1alpha2, v1alpha3, and v1beta1 are no longer served.

Question: When will you convert/update update all your manifests from v*alpha* to v1?

**Comment by pavelmaliy** [comment]
Thank you for your comment
The documentation was updated and new release was created

for releases v0.1.18 or higher use cert manager v1.6.0 or higher
for releases v0.1.17 or lower use cert manager lower then v1.6.0
