### ISSUE TITLE
Question: Is there an ClientSet available to interact with K8s CRD Objects 

### ISSUE THREAD

**Issue by sTb1337** [SAP/sap-btp-service-operator#104]
Is there an ClientSet available to interact with K8s CRD Objects like https://pkg.go.dev/github.com/gardener/gardener/pkg/client/extensions/clientset/versioned?

I have to progamatically update an Service Instance of .Spec ->  serviceOfferingName: identity  servicePlanName: application -> parameters -> oauth2-configuration -> redirect-uris every time a new BTP Subaccount subscribes to my Service which creates an new Gardener Cluster.

Kind regards

**Comment by pavelmaliy** [comment]
Hi,
no currently there is ClientSet available,  we use regular  rest client for now
see [example](https://github.com/SAP/sap-btp-service-operator-migration/blob/main/migrate/migrator.go#L270)

Thanks.
