### ISSUE TITLE
Questions: Comparing Service Catalog and Service Operator from SAP BTP perspective 

### ISSUE THREAD

**Issue by levinanton** [SAP/sap-btp-service-operator#108]
Hello,

we are currently in a process of moving from ["Service Catalog / Service Broker Proxy"](https://help.sap.com/viewer/09cc82baadc542a688176dce601398de/Cloud/en-US/20195bf3b6e64189966e08f669c275e1.html) based setup towards "SAP BTP Service Operator" and I am trying to compare their output from the BTP Sub-Account perspective.

**_Context_**

For having Service Catalog / Broker on your K8s Cluster, it was necessary to register that cluster as "platform":

```sh
smctl register-platform <platform-name> kubernetes
```

then all created service instances appeared  under Sup-Account -> Instances and Subscriptions for a specific scope:

`platform-name | k8s-namespace`

<img width="2030" alt="Screenshot 2021-12-03 at 05 52 09" src="https://user-images.githubusercontent.com/12249110/144548524-31a0e792-4987-4af0-8c1f-f6f194fcbf9e.png">

Of course, it is possible to register multiple clusters as platforms, creating instances using the same name.

Now with SAP BTP Service Operator, instead of a "platform" it is necessary to create an instance of the Service Manager (`service-operator-access` service plan) and respective binding which values will be used as parameters when installing "sap-btp-operator" helm chart.

So far so good but after we start creating app-specific service instances, they appear as `undefined` in BTP Cockpit:

<img width="2049" alt="Screenshot 2021-12-03 at 06 07 18" src="https://user-images.githubusercontent.com/12249110/144548759-acd84b4e-49fd-4b90-8422-1781ce482e52.png">

**_Questions_**

Now, finally the questions:

1. Is it planned to cooperate with BTP Cockpit colleagues to improve on that `undefined` situation? What actually will be shown instead of "platform" when Service Operator based setup is used?

2. If we now create multiple clusters, should we simply re-use already created instance of the Service Manager (`service-operator-access` service plan) and its binding to install "sap-btp-operator" helm chart or are we supposed to create new binding per cluster? What would be the procedure? Creating a new instance of the Service Manager (`service-operator-access` service plan) is not possible, since we are entitled to have one and only one instance per (provider) sub-account.

Thanks in advance,
Anton

**Comment by pavelmaliy** [comment]
Hi,
The instance of the service-manager replaces platform concept,
each instance represents a **single cluster**.

regarding your first question:
it is a bug in the cockpit which I already raised to them not sure when it'll be fixed,
instead of a platform, operator instance should be shown (equivalent to platform)

regarding your second question:
instance == platform you need to create instance per cluster.

> Creating a new instance of the Service Manager (service-operator-access service plan) is not possible, since we are entitled to have one and only one instance per (provider) sub-account. 

I am not sure it's correct `operator-access` plan doesn't have quota checks and defined as "elastic" in CIS, you can create as much as you like per sub-account.
