### ISSUE TITLE
Helm-Chart should support other certificates than jetstack/certificate-manager

### ISSUE THREAD

**Issue by voigt** [SAP/sap-btp-service-operator#111]
Hey btp-service-operator team,

Kyma uses the btp-service-operator. Unfortunately, the default helm chart only supports jetstack/certificate-manager certificates. However, cert-manager is not a default component of a kyma environment. Therefore we created a custom helm chart supporting the following types of certificates:

- Self-Signed
- Jetstack Cert-Manager
- SAP Cert-Management

The helm chart we are using is currently located here: https://github.com/kyma-incubator/sap-btp-service-operator/tree/main/chart

It would be terrific if the official helm-chart provided by sap-btp-service-operator would be extensible enough, so we could get rid of ours.

Regards,
Christoph

**Comment by pavelmaliy** [comment]
Hi,
We're planning to extend the official helm chart to support other certificates including what you have in the custom helm.
For exact timelines you can contact our PO @avilupu .

**Comment by pavelmaliy** [comment]
Hi,
The PR was merged please let me know if everything is OK.
Please note that I only validated the cert manager option, as I am not familiar with Gardener I've only took it from your custom chart as is (hopefully it ok). 
You can now get rid from your chart :-)

**Comment by pavelmaliy** [comment]
Hi,
Are you able to use SAP Cert-Management using the official helm chart?
please provide some feedback as we want to add it to official documentation and test it

**Comment by rufreakde** [comment]
> Hi, We're planning to extend the official helm chart to support other certificates including what you have in the custom helm. For exact timelines you can contact our PO @avilupu .

Would it be possible to allow a values parameter for the operator as:
`existingSecret ` property to be able to reference an already existing kubernetes secret on helm deployment.

related to:
https://github.com/argoproj/argo-cd/issues/1786 
https://github.com/argoproj/argo-cd/issues/1786#issuecomment-545690768

We want to deploy the operator with ArgoCD but it is very hard to send the secret credentials in a declarative manner.
