### ISSUE TITLE
Allow deep flattening of service bindings

### ISSUE THREAD

**Issue by patrickhuy** [SAP/sap-btp-service-operator#114]
Currently the btp operator flattens one level of binding information to the secret. It would be nice to have the option to configure a maximum depth to flatten so deep service keys can be used easier as environment variables.
For example there are service keys like this:
```json
{
"uaa": { "url": "https://someorg.authentication.eu10.hana.ondemand.com/" }
}
```

currently this leads to a key in the secret being created called `UAA` which contain the entry

```json
{ "url": "https://someorg.authentication.eu10.hana.ondemand.com/" }
```

it would be nice if there was a configuration option in the `servicebinding` option to flatten 2 (or more?) levels and create a key in the secret called `UAA_URL` which would contain the value `https://someorg.authentication.eu10.hana.ondemand.com/`

Bonus: if we could also get the option to specify a "prefix" for keys in the secret the secrets could directly map to spring boot environment variable bindings. So something like `prefix: MY_PREFIX_` which would make the key `MY_PREFIX_UAA_URL` instead of just `UAA_URL`

**Comment by pavelmaliy** [comment]
Hi,
Are you familiar with `secretKey` and `secretRootKey` option?
you can get the secret as single key json and in your code you can shape it as you like.

I don't think this feature required, if you introduce manipulation on services binding json it becomes an endless loop of requirements with a lot of use cases.

We prefer to keep it simple basic marshaling or no marshaling at all.
BTW I am not sure how combination of such options should work e.g. secretKey + flatten or secretRootKey + flatten

**Comment by patrickhuy** [comment]
Hi @pavelmaliy - yes I'm aware of the option and after your comment I'm strongly considering using it. The challenge is that with "native" environment variables it's trivial to configure spring boot native functionality, for example OAuth2 enabled http clients provided by Spring security without making any application code. When going the JSON decoding route one has to do some trickery to get it to work (either make a custom PropertySource or understand the respective auto configuration enough to see how to disable it "a little") 

Nevertheless I'll try out how it "feels" with the JSON approach and will get back to you.

I agree that having many ways to rewrite the secret can hold challenges, however from what I've seen secret keys holding JSON data are rather non-standard within the Kubernetes ecosystem and it might therefore be valuable to allow preventing it.

**Comment by patrickhuy** [comment]
Hi @pavelmaliy we did integrate the json binding way via secretKey into our applications and it works out "good enough" for our Spring applications we now always make a construct like this: (where we make one class like "BtpServiceBindings" per Service credentials bound)
```
    @Bean
    public BtpServiceBinding btpServiceBinding(ObjectMapper mapper, @Value("${btpservice.binding}") String binding)
            throws JsonProcessingException {
        return mapper.readValue(binding, BtpServiceBinding.class);
    }
```

which is a little awkward but really not that bad. 
From my side this is fine and I'll therefore close this issue and the related PR
