### ISSUE TITLE
Support for the gardener Cert-Manager

### ISSUE THREAD

**Issue by freegroup** [SAP/sap-btp-service-operator#127]
In the installation description it is mention, that we should/must install the jetstack cert-manager.
Maybe it should be possible to use the Gardener provided cert-manager as well. This reduce the amount of
components to install.

I think the BTP-Operator is mainly use within the BTP environment and for this reason gardener or kyma is the 90% case, isn't it?

**Comment by pavelmaliy** [comment]
Already supported see #111

**Comment by freegroup** [comment]
Is this documented. In the installation instruction it is not mentioned, that we can use gardener or self signed certs
https://github.com/SAP/sap-btp-service-operator#setup

**Comment by pavelmaliy** [comment]
No it's not yet,
This issue was handled as a bug opened by Kyma colleagues.
We'll have BLI to dramatically improve our documentation it needs adjustments and move to stable version and not v1alpha1.
