### ISSUE TITLE
Doc Improvement: Subaccount credentials per namespace

### ISSUE THREAD

**Issue by uwe-klinger** [SAP/sap-btp-service-operator#132]
The BTP Service Operator has a very important feature to bind a namespace to a specific subaccount overriding the binding from the service operator's namespace. There are even two ways to do this: 

1. Create a secret with the name `sap-btp-service-operator` / `sap-btp-service-operator-tls` in the namespace that should be bound
2. Create a secret with the name `<namespace>-sap-btp-service-operator` / `<namespace>-sap-btp-service-operator` in the central namespace.

See: https://github.com/SAP/sap-btp-service-operator/blob/68af5b11d31c1d221493bd5c3b9c18f6743fbb97/controllers/base_controller.go#L65

Could you please add documentaion for these features. I think there is a configuration switch to enable 1. as well.

Thanks & Best regards,
Uwe

**Comment by pavelmaliy** [comment]
Hi,
You're right documentation needs improvement, we are working this sprint on improving documentation this is one of the topics
