### ISSUE TITLE
[Issue] Declarative Setup - Helmchart installation with GitOps pattern and ArgoCD is not possible currently

### ISSUE THREAD

**Issue by rufreakde** [SAP/sap-btp-service-operator#141]
To be able to use [ArgoCD](https://argo-cd.readthedocs.io/en/stable/) for deployment it is necessary for a helm-chart to be deployed declaratively. This is needed for our productive deployment as well later on.

In the case of btp-service-operator helm chart the mandatory parameters are confidential this hinders a declarative setup. In the past there were ways to circumvent this issue but these are not available anymore!
- ~~[Workaround](https://utkuozdemir.org/blog/argocd-helm-secrets/)~~ -> [not working anymore](https://github.com/utkuozdemir/argocd-helm-secret-values-example)
- Using the [--values parameter](https://github.com/SAP/sap-btp-service-operator/issues/87) is also not going to work since these values are secret values and [cant be stored for our declarative deployment](https://github.com/SAP/sap-btp-service-operator/issues/111#issuecomment-1061797452) in this way. (we use [bitnami sealed secrets](https://github.com/bitnami-labs/sealed-secrets) for this purposes)

The cleanest solution is to allow the operator to consume an already existing secret if the property is given!
In this case a setup similar to this [example](https://artifacthub.io/packages/helm/argo/argocd-notifications) with some optional parameters fixes the helm chart installation:
```bash
# usual way (will not be changed)
helm upgrade --install <release-name> sap-btp-operator/sap-btp-operator \
    --create-namespace \
    --namespace=sap-btp-operator \        
    --set manager.secret.clientid=<clientid> \
    --set manager.secret.clientsecret=<clientsecret> \
    --set manager.secret.url=<sm_url> \
    --set manager.secret.tokenurl=<url>
```
```bash
# optional way (actually IMHO recommended way):
helm upgrade --install <release-name> sap-btp-operator/sap-btp-operator \
    --create-namespace \
    --namespace=sap-btp-operator \        
    --set manager.secret.create=< true (default) | false > \
    --set manager.secret.name=<default-secret-name> 
```
This way users can point to an existing secret and allow argoCD to deploy the helmchart and the operator can still get all of its needed information since it would be in the same namespace anyways.

Supporting this feature would allow adoption of the btp-service-operator in a simpler and more future proven way there is demand for this and it is also a better design for k8s deployments if there are confidential parameters (this is just my honest opinion here :) ) .
https://github.com/SAP/sap-btp-service-operator/issues/115 https://github.com/SAP/sap-btp-service-operator/issues/87

Implementation on operator side is simple:
```
if manager.secret.create == true
  helm values are filled
  normal behaviour as before
else
  retrieve values from the secret that is provided in manager.secret.name
  continue normal behaviour as before
```

Best regards,
Rudolf

**Comment by rufreakde** [comment]
I was looking through the code and saw he following property:
`.Values.manager.secret.enabled` for the secret [here](https://github.com/SAP/sap-btp-service-operator/blob/ec3528d15e2cd4af8ed3905b3aa0f0bfdfc7b585/sapbtp-operator-charts/templates/secret.yml#L1).

This means we can replace the secret with our own secret just have to name it accordingly:
`sap-btp-service-operator` like [here](https://github.com/SAP/sap-btp-service-operator/blob/ec3528d15e2cd4af8ed3905b3aa0f0bfdfc7b585/sapbtp-operator-charts/templates/secret.yml#L5).

It would be nice if you could add this usage as an example in your documentation! We will try that.

**Comment by pavelmaliy** [comment]
@rufreakde `.Values.manager.secret.enabled` set to false is a way to go,
you can create the secret by yourself or helm will do it for you.
Basically this is the approach for multi tenant clusters you put `sap-btp-service-operator` secret in your namespace and the operator will find it.

BTW we're planning to drop the naming convention and find the secrets with label selectors.
