### ISSUE TITLE
what cf services can be created by btp operator?

### ISSUE THREAD

**Issue by lizzzcai** [SAP/sap-btp-service-operator#162]
Hi colleagues, 

I want to check what services in cf can be created through btp operator? Previously I am able to create `xsuaa` instance. However, when I am trying to create `postgresql-db`, it is not working. But I can use `cf` to create it.

below is the issue:
```
    - lastTransitionTime: "2022-04-14T03:44:55Z"
      message: ""
      reason: NotProvisioned
      status: "False"
      type: Ready
    - lastTransitionTime: "2022-04-14T03:44:56Z"
      message: 'ServiceInstance create failed: couldn''t find the service offering
        ''postgresql-db'''
      observedGeneration: 1
      reason: CreateFailed
      status: "True"
      type: Failed
    observedGeneration: 1
    ready: "False"
```
by using cf , it is working: `cf create-service postgresql-db development  postgresql-instance -c '{"engine_version": "11"}'`

**Comment by pavelmaliy** [comment]
Hi,
Actually it's decided by each service if it has kubernetes in its supportedPlatforms (in OSB catalog metadata).
If service supports kubernetes you can use it with sap btp operator.
In postgres case I know that it supported only in CF.
