### ISSUE TITLE
Subscribe to Kyma environment using the BTP Operator

### ISSUE THREAD

**Issue by yemramirezca** [SAP/sap-btp-service-operator#180]
Hi Colleagues, 
Is it possible to subscribe to a Kyma Environment using the SAP BTP Operator?
If yes, could you point me to the documentation or an example of how to do this?

For our use case we aim to create programmatically this subscription. 
I am aware that the btp CLI offer this option -> https://youtu.be/bQQAqFJ8-4w?list=PLkzo92owKnVwySEcbf_FCf-ToasK4hXc9&t=444
However, we are using K8s and would like to leverage the BTP Operator for this.

Thanks

**Comment by kerenlahav** [comment]
Hi,
Kyma is an environment and not a service instance, therefore it is not possible to create kyma using the sapbtp operator.

Thanks
