### ISSUE TITLE
How to trigger full reconcile for Binding rotation

### ISSUE THREAD

**Issue by f-blass** [SAP/sap-btp-service-operator#181]
Hi experts,

this might be a foolish question, but I am currently stuck at this topic.
What is the best way to trigger the described "full reconcile" so that a control loop is started for all Service Bindings? Currently regardless of the TTL configuration my old bindings are not deleted, as no control loops are started for them. Even if I modify something on the original binding which triggers another rotation, stale bindings are not deleted. This causes issues, as some services (like objectstore) limit the amount of bindings to 5.

**Comment by kerenlahav** [comment]
Hi,
There is a full reconcile every 10 hours or when the sapbtp operator pod is starting, there is no option to trigger it manually.
Thanks
