### ISSUE TITLE
Feature: Use a service binding from more than one namespace

### ISSUE THREAD

**Issue by yemramirezca** [SAP/sap-btp-service-operator#183]
The sap-btp-operator  is managing all the ServiceBinding resources. Once a service Binding is created, a k8s secret is created behind scenes.
However, if an application is deployed in a different namespace it is not possible for it to access the k8s secret.

A feature that sync/mirrors k8s secrets created by a ServiceBinding in different namespaces would be really useful. 
For example by annotating the service binding as in https://github.com/emberstack/kubernetes-reflector.

**Comment by mikednight** [comment]
can we please have this, it would be extremely helpful

**Comment by loewenstein** [comment]
Do `ServiceBinding` CRs support referencing `ServiceInstance` CRs in a different namespace? This I would indeed consider a very valuable feature.
