### ISSUE TITLE
Migrate Service Operator with all service instances to another k8s cluster

### ISSUE THREAD

**Issue by f-blass** [SAP/sap-btp-service-operator#195]
Hi experts,

is there a possibility to move all service instances of an btp-operator installed on cluster A to another btp-operator installed on cluster B?
There should explicitly no new instances be created on cluster B, since there are already customers depending on the old service instances (for subscriptions and the like)

Might be related to #171

**Comment by f-blass** [comment]
@kerenlahav Can you help here?

**Comment by kerenlahav** [comment]
Currently this is not supported, can you please elaborate on the use case?
why is it needed?  
will the same instance be used in more than one cluster?

**Comment by f-blass** [comment]
Hi @kerenlahav 
no, one instance will only be used on one cluster at the same time. We have a multi-cluster setup and want to migrate instances that were created on cluster A (where they don't belong to) to cluster B. We can't just recreate the instances since customers are already depending on it. Currently our only option is to copy the secrets from cluster A to cluster B.

The same would be needed if we would want to say migrate our infrastructure from AWS to Azure or similar.

**Comment by kerenlahav** [comment]
it is not possible to move instances from cluster to cluster but some services can be shared between clusters.
you can find more information here:
https://cp-control-client-uc2.cfapps.sap.hana.ondemand.com/index.html#/knowledge_center/articles/44a5ed5eb4c145a2a89f9e6e1e5811b0
