### ISSUE TITLE
Looking for documentation on how I setup xsuaa with btp operator.

### ISSUE THREAD

**Issue by rscottwatson** [SAP/sap-btp-service-operator#200]
Hello,

After setting up the btp operator, I am looking for any documentation on how I go about setting up xsuaa with the btp operator.  I created the service instance like this after using varions smctl commands ( maybe I should have used btp cli instead ) 

```
./smctl register-platform scott-test-btp kubernetes -o json 
./smctl provision scott-sm-instance  service-manager service-operator-access --mode sync -o json
./smctl bind scott-sm-instance scott-binding --mode sync -o json

Release "sapbtp-operator" does not exist. Installing it now.
NAME: sapbtp-operator
LAST DEPLOYED: Tue Sep 13 16:53:17 2022
NAMESPACE: sapbtp-operator
STATUS: deployed
REVISION: 1
TEST SUITE: None
```

```
apiVersion: services.cloud.sap.com/v1
kind: ServiceInstance
metadata:
	name:      sre-xsuaa-svc-instance
	namespace: scott
spec:
    serviceOfferingName: xsuaa
    servicePlanName: broker
    externalName: sre-xsuaa-broker
```

However, when I describe the object I get the following message

```
Message:               Error sending request GET /v1/service_instances?attach_last_operations=true&fieldQuery=name+eq+%27sre-xsuaa-broker%27+and+context%2Fclusterid+eq+%2730e6bc80-475d-4e1b-bee5-60e04259a615%27+and+context%2Fnamespace+eq+%27scott%27&labelQuery=_k8sname+eq+%27sre-xsuaa-svc-instance%27: Get /v1/service_instances?attach_last_operations=true&fieldQuery=name+eq+%27sre-xsuaa-broker%27+and+context%2Fclusterid+eq+%2730e6bc80-475d-4e1b-bee5-60e04259a615%27+and+context%2Fnamespace+eq+%27scott%27&labelQuery=_k8sname+eq+%27sre-xsuaa-svc-instance%27: unsupported protocol scheme ""
```

We are trying to have our Azure AKS cluster talk to the xsuaa service.  Is there a colleague within SAP I could talk to?

thanks
Scott

**Comment by kerenlahav** [comment]
Hi Scott, 
There is no need to register a platform, you need to create an instance of "service-operator-access"
Please follow the setup guidelines:
https://github.com/SAP/sap-btp-service-operator#setup
Thanks,
Keren.

**Comment by rscottwatson** [comment]
Hi @kerenlahav 

That happened in the step after I did register-platform.  I wasn't sure I needed the register platform but we had it the script the did the service manager install so I did it here too just in case. 

![image](https://user-images.githubusercontent.com/19327943/190247351-89950731-37cd-4cd4-b7c5-6d28caebe23c.png)

**Comment by kerenlahav** [comment]
registering a platform was for SVCAT, when using the BTP operator there is no need to register a platform

**Comment by kerenlahav** [comment]
Closing the issue since it is handled in a JIRA ticket
