### ISSUE TITLE
Issue while creating service binding using BTP operator.

### ISSUE THREAD

**Issue by Mahi1704** [SAP/sap-btp-service-operator#208]
Hello All,

1. We have recently deployed BTP operator in our kubernetes cluster and following this documentation we created sample service instance and service binding - https://github.com/SAP/sap-btp-service-operator.
2. The yaml files for the same are as follows -
Service instance -
```
apiVersion: services.cloud.sap.com/v1
kind: ServiceInstance
metadata:
    name: btp-operator-oct
    namespace: family-mdcs-dev
spec:
    serviceOfferingName: identity
    servicePlanName: application 

```
Service Binding -
```
apiVersion: services.cloud.sap.com/v1
kind: ServiceBinding
metadata:
    name: btp-operator-oct
    namespace: family-mdcs-dev
spec:
    serviceInstanceName: btp-operator-oct
    parameters:
      credential-type: X509_GENERATED
    credentialsRotationPolicy:
      enabled: true
      rotationFrequency: "6m"
      rotatedBindingTTL: "3m"  
```
5. The repetitive error we are seeing in the logs is -
```
kubectl logs sap-btp-operator-controller-manager-946d7b9fc-f94cf manager -n sap-btp-operator
2022-10-10T11:43:09.070Z    ERROR    controller-runtime.manager.controller.servicebinding    Reconciler error    {"reconciler group": "services.cloud.sap.com", "reconciler kind": "ServiceBinding", "name": "btp-operator-oct-lrzlfa", "namespace": "family-mdcs-dev", "error": "Operation cannot be fulfilled on servicebindings.services.cloud.sap.com \"btp-operator-oct-lrzlfa\": the object has been modified; please apply your changes to the latest version and try again"}
github.com/go-logr/zapr.(*zapLogger).Error 
```
Could you please help us fix this issue?

**Comment by kerenlahav** [comment]
This error is caused when the resource is updated during the reconcile loop and should be resolved automatically in the next resource reconciliation.
Please check the resource's status conditions and attach them here if you see an issue

**Comment by kerenlahav** [comment]
The error is valid and you can not avoid it but the recovery is very quick.
Regarding the credentials rotation, "rotationFrequency" & "rotatedBindingTTL" defines the minimum duration, the rotation is done during the binding's reconcile loop, see further details in the [readme](https://github.com/SAP/sap-btp-service-operator#credentials-rotation)

**Comment by Mahi1704** [comment]
Ok thanks for the information @kerenlahav.
