### ISSUE TITLE
[Feature Request] Custom Service Bindings

### ISSUE THREAD

**Issue by MatKuhr** [SAP/sap-btp-service-operator#212]
Hi, 

I'm from the SAP Cloud SDK development team. We were wondering if you ever considered supporting some form of "custom service (bindings)". This would be a means to deliver information & credentials to an app for something that isn't available in the BTP service marketplace (for K8S).

For example, there are services like Connectivity that are not (or not fully) available on K8S. There, users may need to deploy components or provide configuration themselves. However, to make it work with existing tooling and libraries it would be beneficial if the user could easily assemble the data into a "custom" service binding. That way existing code & tooling that reads from service bindings can continue to work, and the user doesn't have to assemble the secrets fully by themselves.

I think the idea would go somewhat in the direction of [User Provided Services on CloudFoundry](https://docs.cloudfoundry.org/devguide/services/user-provided.html). Essentially, the BTP Service Operator could be helpful in assembling the data into a proper binding format. 

Not sure how much value something like this would actually bring or how a usage of this could look like. But I just wanted to bring up the idea and ask if you have any thoughts on that. Maybe you know more use cases where something like this could be helpful.

Let me know if I should go into more detail for the specific use case of the connectivity proxy.

Thanks & kind regards,
Matthias

**Comment by kerenlahav** [comment]
Hi, Why do you need a custom binding? if you want to store data in k8s you can use a Secret or a ConfigMap, what is the added value of using a binding? The output of a binding is saved in a secret and not in the binding itself.
Thanks,
Keren.
