### ISSUE TITLE
Instance crd is updated in the cluster but not on BTP side

### ISSUE THREAD

**Issue by lgunko** [SAP/sap-btp-service-operator#216]
We are using BTP operator to manage the saas-registry instance. After updating the parameters secret and applying the service instance crd referencing updated parameters secret  - the instance parameters on BTP side didn't get updated.

**Comment by kerenlahav** [comment]
bindings are not updated, create a new binding.

**Comment by loewenstein** [comment]
If bindings are immutable the btp-service-operator should prevent changes and enforce immutability?

**Comment by kerenlahav** [comment]
It does enforce it, but you updated the instance and not the binding, instance update does not affect existing bindings.
