### ISSUE TITLE
dead service instance bindings after testing credential rotation

### ISSUE THREAD

**Issue by Sven1410** [SAP/sap-btp-service-operator#219]
Hi,
we tried to enable the credential rotation feature on several service bindings.
The rotation feature itself works fine. 
But sometimes there are "dead bindings" from a rotation (try) left. These bindings contain always the same error:

ServiceBinding create failed: request POST
        https://service-manager.cfapps.sap.hana.ondemand.com/v1/service_bindings
        failed: StatusCode: 409 Body:
       {"error":"Conflict","description":"binding with same name exists for instance with id ..."}

they are named "xxx-binding-yk1e8s" or similar. The "services.cloud.sap.com/stale" label is also there.
These resources are resisting forever and are not deleted by later control loops or btp-operator restarts.
-->after deleting these resources manually on the cluster - they are still listed in the BTP cockpit. 

This problem occurs in 0.2.7 and 0.3.0.
Please check also my SAP internal issue "NGPBUG-310178" (full .yaml files attached).

(We are deploying with argocd, and have 2 btp-operator pods running - using the provided default helm chart)

any help is appreciated - thanks in advance,
Sven

**Comment by kerenlahav** [comment]
Hi Sven, can you please attach the btp operator log from the time of the stale binding creation? (creationTimestamp: '2022-11-07T19:23:55Z')

**Comment by kerenlahav** [comment]
I found the issue, lets's continue the discussion in "NGPBUG-310178"
