### ISSUE TITLE
serviceofferings and serviceplans service manager endpoints not  exposed

### ISSUE THREAD

**Issue by ptesny** [SAP/sap-btp-service-operator#223]
`/apis/services.cloud.sap.com/v1/` does not expose **serviceofferings** and **serviceplans** endpoints of the service manager API; 
as a result service offerings names and their respective plans must be manually looked up ; that's very tedious and error prone; and  not that much user friendly either.

For instance `Service Manager` service offering name is `service-manager` and it has several plans available:

Plan | Description | Environment |
 --- | --- | --- | 
  **subaccount-admin** | Allows management of resources in the subaccount in which the service instance of this plan was created. This includes managing service instances, bindings and subaccount-scoped platforms. | Cloud Foundry, Kyma, Kubernetes, Other | 
  **subaccount-audit** | Allows read-only access to the resources in the subaccount in which the service instance was created. This includes reading service instances, bindings and subaccount-scoped platforms. | Cloud Foundry, Kyma, Kubernetes, Other | 
  **container** | Allows management of service instances and bindings in a reduced scope. Instances created in a container are not visible when using credentials of other container instances | Cloud Foundry, Kyma, Kubernetes, Other |  
  **service-operator-access** | Provides credentials for SAP BTP service operator to access SAP BTP from a Kubernetes cluster. | Other | 

The service plans could be nicely populated for each service offering using the environment (`kubernetes`) as a filter.

**Comment by kerenlahav** [comment]
checkout https://github.com/SAP/sap-btp-service-operator/blob/809b58c4ba5ed01a3153e7ae86434b9c129703ae/README.md#sap-btp-kubectl-plugin-experimental

**Comment by ptesny** [comment]
That's not what we want; we do not want a plugin that requires an intimate knowledge of the btp operator implementation in a cluster ; all we would like to see is these endpoint exposed as resources with `/apis/services.cloud.sap.com/v1/`

```
{
  "kind": "APIResourceList",
  "apiVersion": "v1",
  "groupVersion": "services.cloud.sap.com/v1",
  "resources": [
    {
      "name": "serviceinstances",
      "singularName": "serviceinstance",
      "namespaced": true,
      "kind": "ServiceInstance",
      "verbs": [
        "delete",
        "deletecollection",
        "get",
        "list",
        "patch",
        "create",
        "update",
        "watch"
      ],
      "storageVersionHash": "********="
    },
    {
      "name": "serviceinstances/status",
      "singularName": "",
      "namespaced": true,
      "kind": "ServiceInstance",
      "verbs": [
        "get",
        "patch",
        "update"
      ]
    },
    {
      "name": "servicebindings",
      "singularName": "servicebinding",
      "namespaced": true,
      "kind": "ServiceBinding",
      "verbs": [
        "delete",
        "deletecollection",
        "get",
        "list",
        "patch",
        "create",
        "update",
        "watch"
      ],
      "storageVersionHash": "*********="
    },
    {
      "name": "servicebindings/status",
      "singularName": "",
      "namespaced": true,
      "kind": "ServiceBinding",
      "verbs": [
        "get",
        "patch",
        "update"
      ]
    }
  ]
}
```

**Comment by kerenlahav** [comment]
I don't understand the use case, if the need is to see the available offerings and plans then the kubectl extension is the answer, you don't need to have any inside knowledge of the btp operator to use it, just the namespace it is installed.
please elaborate on the use case and the expected output.

**Comment by kerenlahav** [comment]
I agree that it is not user friendly, but I don't understand your solution proposal, how would you like the BTP operator to expose the offerings and plans?

**Comment by ptesny** [comment]
same way as BTP operator does to expose **serviceinstances** and **servicebindings**.
BTP's Service Manager (SM) API offers these offerings and plans endpoints out of the box. 
You can look them up in the SM's swagger's definition for instance: https://service-manager.cfapps.{region}.hana.ondemand.com/swaggerui/swagger-ui.html 

if region is eu10 that would be: https://service-manager.cfapps.eu10.hana.ondemand.com/swaggerui/swagger-ui.html

<img width="1227" alt="image" src="https://user-images.githubusercontent.com/52403733/201646932-769d3ad0-e105-4a47-8c9b-3110e5eef0fa.png">



When you retrieve the full list of service plans each service plan record has a guid to its service offering. Thus it is easy to pull out the list os the service offerings for kubermetes environment and then provide the sublist of the available plans.

**Comment by kerenlahav** [comment]
I know these apis, but how do you want the BTP operator to use them? bindings and instances are created by the user, who should create the plans and offerings? in which namespace? who will trigger the initiation? (the offering and plans are not static) how will kyma read them? seems like you have something in mind that i don't see, feel free to schedule a meeting to discuss it.

**Comment by ptesny** [comment]
After our discussion I looked up the following CRD, namely: `servicebindings.services.cloud.sap.com` ; this CRD has the storage of all the service bindings across the cluster; Actually we would need `serviceofferings.services.cloud.sap.com` and `serviceplans.services.cloud.sap.com` CRDs with the storage of all offerings and plans. These 2 CRDs would have to be refreshed either manually on demand or once in a while via for instance a cron job....running in a cluster....until a better mechanism in place.
