### ISSUE TITLE
btp-service-operator values.yaml configured with gardener cert manager

### ISSUE THREAD

**Issue by ptesny** [SAP/sap-btp-service-operator#225]
After having installed the btp-service-operator repo I noticed it is configured to use jetstack cert-manager (cert-manager.io/v1). Could you point me to the values.yaml 

https://github.com/SAP/sap-btp-service-operator/blob/main/sapbtp-operator-charts/values.yaml#L55 

pre- configured with gardener cert manager ?

**Comment by kerenlahav** [comment]
I don't understand the question
you can install the cert manager using kubectl
kubectl apply -f https://github.com/jetstack/cert-manager/releases/download/{VERSION}/cert-manager.yaml
![image](https://user-images.githubusercontent.com/45451976/202143557-9042854e-937f-488c-8292-51cc6e5f691f.png)
