### ISSUE TITLE
credentialsRotationPolicy: what is the credentials rotation notification mechanism?

### ISSUE THREAD

**Issue by ptesny** [SAP/sap-btp-service-operator#232]
Hello, 
what is the credentials rotation notification mechanism? 
in other words how a kyma workload can get notified about a new set of credentials in a binding ?

**Comment by kerenlahav** [comment]
Hi Piotr,
There is no notification triggered by the btp operator, if kyma is watching these resources it can check the "lastCredentialsRotationTime" to check when was the last credentials rotation.

**Comment by ptesny** [comment]
Hi Keren, would you if there is a plan to check on the `lastCredentialsRotationTime` when it comes to standard SAP libraries like @sap/approuter, @sap/xsenv, and others ?

**Comment by kerenlahav** [comment]
I don't know what their plans are, and I'm not sure what is the need, who needs to know if there is a new set of credentials and why?
When the btp operator rotates the credentials the new credentials are stored in the original binding's secret, meaning it is transparent to the using app when the credentials are replaced. why do you need a notification when new credentials are created?

**Comment by ptesny** [comment]
```
When the btp operator rotates the credentials the new credentials are stored in the original binding's secret, meaning it is transparent to the using app when the credentials are replaced. why do you need a notification when new credentials are created?
```
That's true the rotated credentials are stored into the original binding;
The problem is that for instance approuter and other SAP libraries are using the SERVICE_BINDING _ROOT mechanism with the volume mounts to fetch the secrets; that works every time a pod is being restarted but the volume mounts are not being refreshed once a pod is up and running.

**Comment by kerenlahav** [comment]
If they will get notified when the rotation occurred, they will be restarted?

**Comment by ptesny** [comment]
not sure any restart would happen; but if there were a rotation notification then SAP libraries might have a chance to implement a restart accordingly

**Comment by kerenlahav** [comment]
Why not do a periodic restart according to the rotation configuration?
if for example the rotation is every 3 days and TTL is set to 2 days - restart the pod every 4 days

**Comment by ptesny** [comment]
Polling ? this cannot be a client workload burden; Ideally there is a notification event sent and then the client workloads can act accordingly...

**Comment by kerenlahav** [comment]
What are you suggesting? 
How are clients handling it today?

**Comment by ptesny** [comment]
That's relevant for the BTP services and their bindings; 
That's not on me to design the mechanism to refresh the rotated credentials as part of the SERVICE_BINDING_ROOT mechanism
I hope that the maintainers of SAP libraries like @sap/xsenv and others will find a way to handle it gracefully...

**Comment by kerenlahav** [comment]
The BTP operator updates the binding and secret, once a resource is updated in k8s (any update) an event is triggered (by k8s..) and whoever watches the resource will get it, anyway I don't see how the BTP operator can do it for you, this is business logic
_"I hope that the maintainers of SAP libraries like @sap/xsenv and others will find a way to handle it gracefully..."_
This is a question to them...
