### ISSUE TITLE
2022/12/23 09:07:41 http: TLS handshake error from 100.96.9.17:44772: remote error: tls: bad certificate

### ISSUE THREAD

**Issue by madgrape** [SAP/sap-btp-service-operator#234]
Hi, Team,

After upgrading to the latest version: v0.3.3, we got errors in pod log here:

<img width="1789" alt="image" src="https://user-images.githubusercontent.com/6726729/209311465-a082831f-d568-4824-b84f-cea73a71715b.png">

**Comment by kerenlahav** [comment]
Hi,
I've installed version 0.3.3  with cert manager (1.6.1) on my cluster and I don't see the issue
<img width="1747" alt="image" src="https://user-images.githubusercontent.com/45451976/209462965-b99432bb-9c62-43af-9308-f64d64a1443d.png">
<img width="502" alt="image" src="https://user-images.githubusercontent.com/45451976/209463014-a558350a-7518-417f-a961-6ada7a204fbb.png">
Which certificate are you using?

**Comment by madgrape** [comment]
HI, Kerenlahav,

<img width="1017" alt="image" src="https://user-images.githubusercontent.com/6726729/209489013-ed7addb4-7848-4db4-b458-63dbcb7ea851.png">

We use the default install config of the operator chart, so we do not clear on which certificate the operator is using.
The volume on the operator po here:
  volumes:
  - name: cert
    secret:
      defaultMode: 420
      secretName: webhook-server-cert
  - name: kube-api-access-bqcqk
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace

**Comment by kerenlahav** [comment]
The certificate's screenshot you attached is missing the .status section, can you please share it?
<img width="510" alt="image" src="https://user-images.githubusercontent.com/45451976/209524352-fe3a12f3-aeef-4a23-844e-378d5094c6f9.png">
Which version of cert-manager are you using?

**Comment by madgrape** [comment]
Hi, @kerenlahav,
After our infra team fixed the cert manager issue on our cluster, the problem has gone.
