### ISSUE TITLE
all the serviceInstances status change to be deleted after upgrading to the latest version: v0.3.3

### ISSUE THREAD

**Issue by madgrape** [SAP/sap-btp-service-operator#235]
Hi, Team,

A more critical issue we found after we upgraded to the latest version v0.3.3 is all the serviceInstances are became deleted status:
<img width="1253" alt="image" src="https://user-images.githubusercontent.com/6726729/209312417-cba17ea4-d354-42e9-a3b5-aff8f774eb27.png">

How could we recover from this situation?

**Comment by kerenlahav** [comment]
Hi,
I upgraded from release 0.2.9 to 0.3.3, and the issue did not reproduce; which version you used before the upgrade?
please share the update command you used and the operator access instance id to check if the instances are recoverable.
Thanks.

**Comment by kerenlahav** [comment]
tested also an upgrade from 0.2.7 and instances kept their state and not got deleted

**Comment by saoDiSengTank** [comment]
Hi @kerenlahav we upgrade from 0.2.7 to 0.3.3 , and will request for update command from SRE team.
BTW , i am not sure which content will help to check if the instances can be recoverable. So i post all our CR content here and hope it will help.

apiVersion: services.cloud.sap.com/v1
kind: ServiceInstance
metadata:
 annotations:
   kubectl.kubernetes.io/last-applied-configuration: >
     xxxxxx
 creationTimestamp: '2022-08-04T02:37:15Z'
 deletionGracePeriodSeconds: 0
 deletionTimestamp: '2022-12-15T10:11:32Z'
 finalizers:
   - services.cloud.sap.com/sap-btp-finalizer
 generation: 2
 labels:
   argocd.argoproj.io/instance: xxx
   cic.sap.com/managed-by: xxx
 managedFields:
   - apiVersion: services.cloud.sap.com/v1alpha1
     fieldsType: FieldsV1
     fieldsV1:
       f:metadata:
         f:annotations:
           .: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
         f:labels:
           .: {}
           f:argocd.argoproj.io/instance: {}
           f:cic.sap.com/managed-by: {}
       f:spec:
         .: {}
         f:serviceOfferingName: {}
         f:servicePlanName: {}
     manager: argocd-application-controller
     operation: Update
     time: '2022-08-04T02:37:14Z'
   - apiVersion: services.cloud.sap.com/v1alpha1
     fieldsType: FieldsV1
     fieldsV1:
       f:status:
         .: {}
         f:ready: {}
         f:tags: {}
     manager: manager
     operation: Update
     subresource: status
     time: '2022-08-04T02:38:55Z'
   - apiVersion: services.cloud.sap.com/v1
     fieldsType: FieldsV1
     fieldsV1:
       f:status:
         f:conditions: {}
         f:observedGeneration: {}
     manager: manager
     operation: Update
     subresource: status
     time: '2022-12-23T09:07:56Z'
 name: xxx
 namespace: xxx
 resourceVersion: '1360654587'
 uid: 3c005ed1-8244-40bc-9f03-0c0b96930e8c
 selfLink: >-
    xxx
status:
 conditions:
   - lastTransitionTime: '2022-12-23T09:08:59Z'
     message: ServiceInstance deleted successfully
     observedGeneration: 2
     reason: Deleted
     status: 'True'
     type: Succeeded
   - lastTransitionTime: '2022-08-04T02:38:55Z'
     message: ''
     reason: Provisioned
     status: 'True'
     type: Ready
 observedGeneration: 2
 ready: 'True'
 tags:
   - xx
spec:
xxxx

**Comment by kerenlahav** [comment]
Hi,
There is no identifiers I can use to fetch your account from this instance. 
you can get the operator-access instance id from a secret named sap-btp-service-operator in namespace sap-btp-operator, please share the clientid and sm_url values.

The deletion does not seem to be related to the upgrade of the btp operator (the deletion timestamp of the resource is way before the upgrade), I see you are using argo which might be related.

If the instances still exist in Service Manager we will be able to recover them, if not then you will have to recreate them.

**Comment by saoDiSengTank** [comment]
Hi , i checked the secret you mentioned , and the clientid and sm_url values are all empty.
<img width="626" alt="Screenshot 2022-12-27 at 18 17 48" src="https://user-images.githubusercontent.com/102742059/209652391-af144f6b-633c-4f8f-a5d2-a61450e43050.png">

**Comment by kerenlahav** [comment]
Do you know the subaccount id and landscape?
please share the content of configmap "sap-btp-operator-config" in namespace sap-btp-operator

**Comment by saoDiSengTank** [comment]
Hi @kerenlahav 
To avoid sensitive data shows here , how about we communicate with teams or email ?
You can reach out to me by email changli.zhang@sap.com or teams c5289702

**Comment by kerenlahav** [comment]
Hi, please schedule a 1 hour teams meeting to sync and resolve this issue, we will need to access the cluster.

**Comment by saoDiSengTank** [comment]
Hi @kerenlahav , that's perfect if we can sync by meeting , what's your avilable time ?
