### ISSUE TITLE
Please provide arm64 image

### ISSUE THREAD

**Issue by cbarbian-sap** [SAP/sap-btp-service-operator#236]
We want to use clusters running on AWS Graviton (recently Gardener was released for linux/arm64).
For this, we need an arm64 compiled image of btp-service-operator.

Can you please provide such?

**Comment by cbarbian-sap** [comment]
This is still relevant, can you please comment on this ?

**Comment by kerenlahav** [comment]
We added this issue to the backlog and it will be prioritized in the next takt.
