### ISSUE TITLE
429 error when trying to provision BTP services

### ISSUE THREAD

**Issue by ptesny** [SAP/sap-btp-service-operator#239]
Hello, I understand the service manager service_offerings API endpoint observes a rate limit. However, in most of the cases people miss to spot the initial error and then they report 429 error instead;

Also sometimes the number of retries is very high like 1000 and sometimes it is way lower like 50;

Are you planning to retain the initial error message that will lead eventually to receiving 429 error?
Is there a way to set the max number of retries on btp service operator side so we do not meet the 429 error condition?
kind regards;

**Comment by kerenlahav** [comment]
indeed a bug, that error should not be reflected to the user, will be fixed in the next release.
