### ISSUE TITLE
use separate service account rather than default

### ISSUE THREAD

**Issue by runzexia** [SAP/sap-btp-service-operator#244]
To fix the security issues, the security team request us to `Remove Default Service Account Token`, and we found that the btp operator depends on the default service account, which cause us hard to apply the global policies via `kyverno`

**Comment by kerenlahav** [comment]
We are currently working on creating a dedicated service account for the BTP operator, it should be available in the next release

**Comment by runzexia** [comment]
Thanks for your quick reply, could you give an excepted date of release, so we could better plan our release

**Comment by kerenlahav** [comment]
resolved in v0.3.7
