### ISSUE TITLE
Is it possible to specify a service broker name upon `ServiceInstance` CRD creation?

### ISSUE THREAD

**Issue by geigerj0** [SAP/sap-btp-service-operator#251]
### Context
I have a question regarding a [`ServiceInstance` creation according to your specification](https://github.com/SAP/sap-btp-service-operator#service-instance) on a Kubernetes cluster.

The specification of the CRD doesn't mention a possibility to set a broker name. 

Looking at the `provision` command of the Service Manager CLI, setting a specific broker name is possible via `--broker-name`: https://github.com/Peripli/service-manager-cli/blob/master/docs/commands/provision.md. 

Looking at the `create-service` command of the Cloud Foundry CLI, setting a specific broker name is possible via `-b`: https://cli.cloudfoundry.org/en-US/v6/create-service.html

### My Question
Is it possible to specify a service broker name upon `ServiceInstance` CRD creation?

**Comment by kerenlahav** [comment]
No, it is not possible to specify a broker name.
Setting a broker name is used to solve ambiguity issues, in Kubernetes this is solved by adding the service plan id to the spec
<img width="856" alt="image" src="https://user-images.githubusercontent.com/45451976/218300922-ce0fc5a2-ee6a-4f12-8b1d-19b31354a629.png">
