### ISSUE TITLE
Secret created for service binding cannot be labelled

### ISSUE THREAD

**Issue by k15r** [SAP/sap-btp-service-operator#259]
In kyma we use the btp-service-operator to create service bindings for eg. Event Mesh. To switch eventing in kyma to use event mesh as its backend we rely on being able to label the created secret with a specific label.

Currently the operator does not allow adding a custom label to the secret. 

**How to reproduce**
1. Create a service binding using the operator
2. apply any custom label to the secret that is created as a result of the service binding

**What should happen**
- The secret should not be modified by the operator again and the label should stay on the secret

**What actually happens**
- seconds after applying the label, that change is reverted by the operator

If adding a label directly to the secret is not an option, please allow adding custom labels to the service binding, that then will be applied to the secret created by the operator

**Comment by kerenlahav** [comment]
I was not able to reproduce the issue, which version of the operator are you using?
The operator does not set any labels on the secret, when I tested it the added label remained.

**Comment by loewenstein** [comment]
1. I don't think that it is safe to assume that a controlled resource, in this case the `Secret`, can be modified directly and isn't later touched and changed by the controller, in this case the btp-service-operator.
2. Taking credential rotation into account, even if the current btp-service-operator implementation allowed for adding labels, I would suppose this does not extend to higher level operational features like rotation that might end up exchanging the controlled resources transparently.
   Given that the btp-service-operator replaces credentials in place, this might actually work, but I would not accept this as an api contract if I would be owning the btp-service-operator.

**Comment by yuvalman** [comment]
Hi @loewenstein / @kerenlahav,
This is an important feature that can help with selecting secrets by label.

Can you please /reopen it?

@loewenstein,
Regarding the points you mentioned.
1. if someone will use the feature (adding the option to add labels/annotation to a created secret by the service binding), why do we assume that we cannot modify the secret directly? We can add logic inside the controller that will manage only the custom labels added by it, and the user will be able to modify other labels as he wishes.
2. Regarding the rotation, I'm not sure why it should be a problem. In case you are adding logic for adding label for a secret that is created by binding, we should just use the same logic for updating the old service binding. I can see in the [code](https://github.com/SAP/sap-btp-service-operator/blob/8efd50e6d8496c98b47eaa48f998360c33de3810/controllers/servicebinding_controller.go#L874), that the old binding is created with just a different secret name but with the same logic of binding creation.

Why not add/expand the spec of service binding to have a secretTemplates field:
```
...
  spec:
    credentialsRotationPolicy:
      enabled: false
      rotatedBindingTTL: 2184h
      rotationFrequency: 2016h
    externalName: binding-<old-suffix>
    secretName: binding-secret-<old-suffix>
    secretTemplates:
      labels:
        a: a
     annotations:
       b: b
...
```
In this case, you can just add the same labels/annotations to the old created secret
