### ISSUE TITLE
Delete Service Instances with `DELETE FAILED` State

### ISSUE THREAD

**Issue by sidakphull** [SAP/sap-btp-service-operator#263]
I have a couple of instances (saas-registry and xsuaa) which are stuck in DELETE FAILED state. I tried using the command mentioned in the Troubleshoot to delete them:

`smctl bind INSTANCE_NAME BINDING_NAME --param force_k8s_binding=true` 

But I get the following error when I try to execute this command in the terminal:

`Error: request POST https://service-manager.cfapps.sap.hana.ondemand.com/v1/service_bindings?async=true&force_k8s_binding=true failed: StatusCode: 400 Body: {"error":"Bad Request","description":"sapcp operator must provide _clusterid, _namespace and _k8sname labels"}`

I wasn't able to find any documentation on how to pass the labels to the bind command. Any idea how to proceed here?

Thanks

**Comment by kerenlahav** [comment]
The error is caused because you are using the operator's credentials, you need to login as subaccount admin
