### ISSUE TITLE
cannot use plan "service-operator-access" for subscription of "service-manager"

### ISSUE THREAD

**Issue by Sven1410** [SAP/sap-btp-service-operator#265]
we are using "btp service operator" to manage our BTP service subscriptions inside our k8s cluster.
this works fine so far, this btp-operator uses credentials which are manually created in BTP cockpit. 
these manually created subscription is of type "Service: Service Manager (service-manager),  Plan: service-operator-access" 

Now we want ro rotate this credentials as described here: https://github.com/SAP/sap-btp-service-operator
(searching for "In order to rotate the credentials between the BTP service operator and Service Manager")

for that we need now another subscription of "service-manager" and Plan: service-operator-access" which is managed by the btp-operator itself.
The creation of this subscription always fails with the error: 

      message: >-
        ServiceInstance create failed: couldn't find the service plan
        'service-operator-access' for the service offering 'service-manager'
        
--> I can create subscriptions of plan type "subaccount-admin" but that is not useful - because that is the wrong plan.
      so my service definition is ok I think
Something must be wrong with this plan type "service-operator-access" in our BTP account.
Is there a limit of subscriptions of this plan type ? are X.509 credentials required (I'm using clientid/clientsecret)? 

btp operator version:  0.3.0 
I also created a SAP internal ticket "NGPBUG-347429"

**Comment by kerenlahav** [comment]
There is no automatic credential rotation for the operator's credentials, you cannot create plan "service-operator-access" in the cluster itself, you should create a new binding for the existing instance through cockpit or SM api, once you have the new credentials run helm upgrade command with it.

**Comment by Sven1410** [comment]
.., thanks for the fast reply. We had the expectation that it works like for all other service binding credentials (with credentialsRotationPolicy: enabled: true) ;-( 
please confirm that we cannot use this mechanism.
So the only way to have an automated rotation is to create a new binding with smctl cli tool, then update the secret and restart btp operator ?

**Comment by kerenlahav** [comment]
you cannot configure credential rotation for bindings that were not created within the cluster (service-operator-access instance is created in SMaaP and not k8s).
Currently there is no automatic way to rotate the operator's creds

**Comment by Sven1410** [comment]
... I wanted to add - maybe someone has the same task - that I have now an automated rotation for the 
"service-operator-access" binding in place. It works, like suggested, with SM API:

- I created a (second) service manager instance and binding with plan "subaccount-admin" in the cluster
- this binding can rotate its own credentials using the automated mechanism "credentialsRotationPolicy enabled: true"
- using these credentials with "smctl" (https://github.com/Peripli/service-manager-cli) you can recreate the binding for "service-operator-access"
- this "smctl" bind/unbind runs in a short bash script inside an Argo Workflows container
- after renewal of the binding the credentials for btp-service-operator are updated and the deployment is restarted - automated with Argo CD
