### ISSUE TITLE
service instance cannot delete and recover with pending status after i delete it in argoCD.

### ISSUE THREAD

**Issue by ekko100120** [SAP/sap-btp-service-operator#276]
After i delete service instance in argoCD, the service instance can not be deleted with status `Deletion Failed`

and the error log as below:

`"error": "request DELETE https://service-manager.cfapps.us21.hana.ondemand.com/v1/service_instances/1ef6fef8-a747-4a91-a906-207b894d5250 failed: StatusCode: 502 Body: {\"error\":\"BrokerError\",\"description\":\"Failed deprovisioning request instanceID: 1ef6fef8-a747-4a91-a906-207b894d5250, planID: data-privacy-integration-service-application, serviceID: data-privacy-integration-service, acceptsIncomplete: true: Status: 422; ErrorMessage: \\u003cnil\\u003e; Description: Their are active subscriptions present hence cannot delete service instace; ResponseError: \\u003cnil\\u003e\"}`

<img width="1301" alt="image" src="https://user-images.githubusercontent.com/18352566/229678938-05d9bae9-e6c7-4dfa-8784-9b46da6353d4.png">

and when i want to  recover it. this service instance also can not be recovered, the error log as below 
`"service instance 'rgm-test-dpi' is not usable"`
<img width="1300" alt="image" src="https://user-images.githubusercontent.com/18352566/229678820-1a91930f-8f2d-462e-831d-9953bf43bc05.png">

is there a way to stop this intermediate state, and we can delete it or recover it  to termidiate state?

**Comment by I065450** [comment]
hi @ekko100120 
Please delete the active subscriptions and the instance will be deleted.

Regards,
Naama
