### ISSUE TITLE
BTP Operator latest version upgrade error

### ISSUE THREAD

**Issue by SovithKothari** [SAP/sap-btp-service-operator#277]
Hi,

We tried to upgrade to latest btp operator chart version and got the following error:

rpc error: code = Unknown desc = `helm pull --destination /tmp/e9d9eb19-d39a-44e6-be3f-7fe0e8a722d2 --version v0.4.2 --repo https://sap.github.io/sap-btp-service-operator sap-btp-operator` failed exit status 1: Error: chart "sap-btp-operator" version "v0.4.2" not found in https://sap.github.io/sap-btp-service-operator repository

Can you please help me in finding and updating the latest chart version?

**Comment by I065450** [comment]
Hi @SovithKothari 

Please try again now.

Regards,
Naama
