### ISSUE TITLE
Restore service-manager for the kyma cluster in the BTP subaccount

### ISSUE THREAD

**Issue by zc11818** [SAP/sap-btp-service-operator#290]
Hi team,

I encountered a problem with the connection between Kyma and BTP. I accidentally deleted the service-manager instance in my BTP subaccount. This service-manager instance is a connection tool between Kyma and the BTP subaccount，it was created by kyma system automatically.  I would like to know how I can restore it? 

Thanks.

**Comment by kerenlahav** [comment]
Hi, 
There is no way to recover a deleted instance, you need to recreate the KYMA environment.
