### ISSUE TITLE
Missing instance_external_name in binding secret .metadata

### ISSUE THREAD

**Issue by ptesny** [SAP/sap-btp-service-operator#291]
It looks like that's pretty much the only field that is excluded from a binding secret `.metadata` section.

What it means is that the @sap/xsenv is unable to fetch the value of `instance_external_name`;
Of course one could add this field manually to each secret's .metadata section but it is neither practical nor doable at scale.

Could you please make sure all the standard fields of a binding secret have their representation in the .metadata section ?

**Comment by ptesny** [comment]
@kerenlahav , any idea if and when it could be done ? many thanks;

**Comment by ptesny** [comment]
hi @kerenlahav , any news on this ?

**Comment by ptesny** [comment]
hi @kerenlahav ; done; the missing `instance_external_name` is used by the SAP BTP extensibility services. The value of `instance_external_name` would be become the name of the destination created on a sub-account level (via api-access service plan); The fact that the name of the destination cannot be retrieved from a secret is more of a bug then a feature request... my 2 cents

**Comment by avilupu** [comment]
Hi. Having the 'external_instance_name' key in the created secret was a bug. A fix is delivered with [release v0.5.3](https://github.com/SAP/sap-btp-service-operator/releases/tag/v0.5.3).
In the created secret, the value of the 'instance_name' key is the BTP name, which is maintained in the external name property of the binding, not in the metadata name.
'external_instance_name' key was removed from the secret.
