### ISSUE TITLE
Pre-delete-job image - allow customization of helm repository

### ISSUE THREAD

**Issue by gadisn** [SAP/sap-btp-service-operator#294]
We have a scenario where we need to consume images from a corporate helm repository, so we need to override the pre-delete-job image (like we do for the manager).

In addition, we need to support pull request for that repository

**Comment by gadisn** [comment]
Suggested fix: https://github.com/SAP/sap-btp-service-operator/pull/293

**Comment by kerenlahav** [comment]
fix merged and released in version v0.4.8
