### ISSUE TITLE
Service instance DELETIONFAILED state not resolvable

### ISSUE THREAD

**Issue by lholthof** [SAP/sap-btp-service-operator#299]
Hi team,

I am running applications based on Kyma which uses SAP BTP Service Operator. My issue is that for service instances which have a state DELETIONFAILED I am in a stuck situation as I cannot resolve this state by updating the service instance. Furthermore any bind request is denied because of the erroneous state of the service instance.

A sample of this situation is created by updating the argocd appset of my cluster which leads to deletion and recreation of the ressources. There for example my xsuaa service instance cannot just be deleted as there are still external resources using this instance (e.g. subscriptions / clones). Same situation I had with auditlog service and cloud logging service.

From my experience in the CF environment, it is okay to fail such a deletion request, but afterwards somehow the service instance has to become usable again, as I will never be able to cleanup subscriptions/clones of an widely adopted instance.
Therefore I ask you to comment on my situation and suggest a mitigation, how to turn the service instance into a usable/active instance again.

Thanks, Lukas

**Comment by ptesny** [comment]
I've a gut feeling you must be having like active BTP subscriptions or so; 

If this were the case you could forcibly remove the subscriptions using the BTP side subscription management dashboard and then you would see the failed instances on kyma side would be removed after some time (10-20 minutes)

**Comment by kerenlahav** [comment]
Hi @lholthof 
can you please explain why argo cd recreates the instance instead of updating it? 
check out the [troubleshooting section](https://github.com/SAP/sap-btp-service-operator#troubleshooting-and-support), there is a solution for this exact scenario.
Thanks,
Keren.

**Comment by kerenlahav** [comment]
resolved
