### ISSUE TITLE
shared instance creation throws 500 error in BTP cockpit

### ISSUE THREAD

**Issue by prasad03kp** [SAP/sap-btp-service-operator#300]
I have a scenario where I want to manage and rotate secrets of existing service instances created using terraform from Kubernetes cluster. So I created a new test instance using terraform and trying to connect to same service instance from k8s cluster using `shared` property of sap-btp-service-operator. It created service instance successfully in cluster. But after creation, when I try to check service instances from BTP cockpit, it throws `500 Network error`. However I can see the shared instance when I login through cf cli. How can I resolve this error? Please redirect me to the right location if this is not the right place to ask this question.

Thanks in advance !

**Comment by kerenlahav** [comment]
what is the instance status in the cluster?
if you see the error only in the cockpit please open a ticket to the cockpit team.

**Comment by prasad03kp** [comment]
I see Created status in cluster. I will close this issue for now and raise issue for btp. Thank you !
