### ISSUE TITLE
After gardener shoot cluster upgrade to v.1.25.10, btp-operator pod failed to run

### ISSUE THREAD

**Issue by janezhen08** [SAP/sap-btp-service-operator#306]
Hello Team,

We have upgraded gardener shoot cluster to v.1.25.10, after upgrade, found that the pods are crashing

sap-btp-operator-controller-manager-7fd78845bb-6c5lz              1/2     CrashLoopBackOff   3 (23s ago)    2m56s
sap-btp-operator-controller-manager-7fd78845bb-vl79j              1/2     CrashLoopBackOff   3 (41s ago)    3m13s

Error logs as below:

2023-07-21T07:13:35.188Z	ERROR	controller-runtime.source	if kind is a CRD, it should be installed before calling Start	{"kind": "ServiceBinding.services.cloud.sap.com", "error": "no matches for kind \"ServiceBinding\" in version \"services.cloud.sap.com/v1\""}
github.com/go-logr/zapr.(*zapLogger).Error
	/go/pkg/mod/github.com/go-logr/zapr@v0.2.0/zapr.go:132
sigs.k8s.io/controller-runtime/pkg/source.(*Kind).Start
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.7.0/pkg/source/source.go:117
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.7.0/pkg/internal/controller/controller.go:159
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.7.0/pkg/internal/controller/controller.go:205
sigs.k8s.io/controller-runtime/pkg/manager.(*controllerManager).startRunnable.func1
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.7.0/pkg/manager/internal.go:691

Please have a look and advise how to fix.

thanks

Jane

**Comment by janezhen08** [comment]
The helm chart version is sap-btp-operator-v0.2.5

**Comment by TalShorSap** [comment]
Hi,

Can you please try updating the operator version? (0.4.8 is the latest, your version is older than a year)

**Comment by janezhen08** [comment]
Hello Team,

We installed this sap-btp-operator-v0.2.5 chart in many other DCs, it has no problem.
Also today, i redeployed the shoot cluster and redeploy the btp-operator service, this time, the installation is successful.
We would like to know the root cause why sometimes it failed and it even removed the CRD resources, and removed the serviceinstance and servicebinding, we can't afford to lose these serviceinstance and servicebinding in production, so we would like to know the root cause to prevent such cases occuring in our production DCs.

**Comment by kerenlahav** [comment]
Hi Jane,
How is the CRDs **deletion** related to the BTP operator deployment? 
You upgraded the cluster and the CRDs were deleted, therfore you should check what was wrong in the upgrade process.
If you have a specific failure of the operator please attach it, anyway we will not support issues in this operator version since it is outdated (not relevant for this issue which is related to the cluster and not the operator)

**Comment by janezhen08** [comment]
the issue has been resolved after redeploying.
