### ISSUE TITLE
label and annotations for service binding secrets

### ISSUE THREAD

**Issue by prasad03kp** [SAP/sap-btp-service-operator#307]
Hi,

I have a use case where I want to replicate service binding secrets created using btp-operator to multiple namespace. I have Kubernetes replicator installed on my cluster which looks for some specific annotations and labels in secret yaml and replicates it across allowed namespaces. So I am just wondering if there is any way I can add custom annotations and labels to secrets created using service bindings using service binding yaml templates.

Thanks,
KP

**Comment by kerenlahav** [comment]
currently there is no option to add labels on the secret from the binding, it is possible to add a label directly on the secret.
Can you elaborate on the use case? why do you need to replicate the secret?

**Comment by prasad03kp** [comment]
@kerenlahav Thank you for responding. We have instances such as auditlog which is shared across multiple apps in different namespace and we use Kubernetes replicator to copy secrets from global-secrets namespace to application namespace based on labels. So it is important for us to label the secrets

**Comment by TalShorSap** [comment]
We are currently considering this feature request.
Update will be provided when relevant

**Comment by kerenlahav** [comment]
Hi @prasad03kp 
Until this feature is evaluated, maybe you can use a new feature that is already included in the latest version - create a binding for an instance from another namespace.
just add 'serviceInstanceNamespace' to the binding's spec and set the relevant namespace. example:
`apiVersion: services.cloud.sap.com/v1
kind: ServiceInstance
metadata:
  name: sample-instance-1
  namespace: **test1**
spec:
  serviceOfferingName: service-manager
  servicePlanName: subaccount-admin
---
apiVersion: services.cloud.sap.com/v1
kind: ServiceBinding
metadata:
  name: sample-binding-1
  namespace: **test2**
spec:
  serviceInstanceName: sample-instance-1
  serviceInstanceNamespace: **test1**
`
Thanks,
Keren
