### ISSUE TITLE
failed to update objectstore serviceinstance params using sm api

### ISSUE THREAD

**Issue by janezhen08** [SAP/sap-btp-service-operator#308]
Hello Team,

After we upgrade btp-operator from sap-btp-operator-v0.2.5 to sap-btp-operator-v0.4.8, we failed to use SM api to update objectstore serviceinstance's param.

We followed this docs: https://api.sap.com/api/APIServiceManagment/resource/ and use patch method to update objectstore serviceinstance's param to enable preventDeletion flag per docs: https://help.sap.com/docs/object-store/object-store-service-on-sap-btp/prevent-accidental-deletion-of-aws-s3-buckets,

But error is: 405 Method Not Allowed

But before the upgrade, we are using sap-btp-operator-v0.2.5, we are able to use patch method to update objectstore serviceinstance's param.

Could you take a look and help fix.

thanks

Jane

**Comment by TalShorSap** [comment]
Can you please provide information so we can debug your request?
instance-id?
landscape?
(any useful information) 

And please attach the logs from the cluster failure if possible.
Thx.

**Comment by TalShorSap** [comment]
@janezhen08  Please close the issue if you have no more questions
