### ISSUE TITLE
Endpoint for metrics

### ISSUE THREAD

**Issue by yemramirezca** [SAP/sap-btp-service-operator#324]
When deploying the helm chart for btp service operator, the Service "sap-btp-operator-controller-manager-metrics-service" is created. 
Is there an /metrics that could be used for monitoring? if yes, as the service is protected (https), how could we access it?

**Comment by TalShorSap** [comment]
You can read about it here - https://book.kubebuilder.io/reference/metrics.html

Its a default tool for prometheus to collect metrics
