### ISSUE TITLE
Configuring operator to use gardener cert manager fails aquiring webhook-server-cert

### ISSUE THREAD

**Issue by krodyrobi** [SAP/sap-btp-service-operator#328]
Considering the operator chart can configure [garden cert resources](https://github.com/SAP/sap-btp-service-operator/blob/main/sapbtp-operator-charts/templates/gardener-cert-manager-certificate.yml#L15) and the [values](https://github.com/SAP/sap-btp-service-operator/blob/main/sapbtp-operator-charts/values.yaml#L67) permit overriding, I'd expect it to work on a default gardener shoot.

```
 <normal helm install from documentation>
 --set manager.certificates.certManager=false \
 --set manager.certificates.gardenerCertManager.issuer=garden \
```

Unfortunatelly the hardcoded configured [cert commonName](https://github.com/SAP/sap-btp-service-operator/blob/main/sapbtp-operator-charts/templates/gardener-cert-manager-certificate.yml#L9) does not pass acme validation. 

```
Warning  reconcile  4m44s (x3 over 12m)  cert-controller-manager  obtaining certificate failed: acme: error: 400 :: POST :: https://acme-v02.api.letsencrypt.org/acme/new-order :: urn:ietf:params:acme:error:rejectedIdentifier :: Error creating new order :: Cannot issue for "kubernetes": Domain name needs at least one dot (and 2 more problems. Refer to sub-problems for more information.), problem: "urn:ietf:params:acme:error:malformed" :: Error creating new order :: Domain name needs at least one dot, problem: "urn:ietf:params:acme:error:malformed" :: Error creating new order :: Domain name does not end with a valid public suffix (TLD), problem: "urn:ietf:params:acme:error:malformed" :: Error creating new order :: Domain name does not end with a valid public suffix (TLD)
```

Version: 0.5.1

Can you guys have a look?

**Comment by krodyrobi** [comment]
After looking some more on gardener it seems that the cert-manager managed by the cluster only accepts acme / dns validations and will not work for local svc, and having a custom CA that does not get rotated is not that great.

Do you know if it is appropiate to have a second vanilla cert-manager? (even though the online docs say funkiness might occur if 2 of them are running)

**Comment by kerenlahav** [comment]
Hi,
We don't support cluster configuration, if you need to configure values that are currently not present in the values.yaml feel free to request it and we'll evaluate it.
Thanks,
Keren.

**Comment by krodyrobi** [comment]
It seems to work even in gardener having a vanilla cert-manager installed so not an issue.
