### ISSUE TITLE
Using separate namespace service secrets, deleting the namespace directly causes namespace to hang

### ISSUE THREAD

**Issue by krodyrobi** [SAP/sap-btp-service-operator#331]
Consider the layout

namespace X:
  - ServiceInstance
  - ServiceBinding
  - sap-btp-service-operator secret

namespace sap-btp-operator:
  - default install secret.enabled turned off or default chart values

Delete namespace X
 -> can no longer add secret to namespace as ns pending deletion
 -> service instance / binding deletion hanging as no secret or trying to use default empty from sap-btp-opertor namespace
 
Only way to recover is manually create secret again in operator namespace and perform a rollout on it's deployment.

**Comment by TalShorSap** [comment]
Can you please emphasis the main issue? 

Why in namespace X you have the other namespace secret?

**Comment by krodyrobi** [comment]
So the helm namespace for the operator is sap-btp-operator it contains nothing except the things installed by the helm without the secret for BTP service manager (would not want to have a default subaccount shared accross namespaces, it wouldn't make sense to use one subaccount for creation and another for deletion, see below), nor any in the format sap-btp-service-operator-<namespace>, in other words if you'd create a custom resource anywhere at this point no credentials for SM exist in the cluster.

The other namespace (custom app namespace) has the instance + binding  and a secret named `sap-btp-service-operator`.
The binding and instance get created with this secret all fine.

The moment when I issue `kubectl delete namespace <custom-app-namespace>` k8s deletes the secret and then notifies the hook of the operator to delete the instances/bindigs but at that point the namespace's secret is already gone - deadlock.

- You cannot add the secret back in the namespace as the namespace is pending deletion.
- Putting the `sap-btp-service-operator-<namespace>` secret in the operator's namespace won't work alone, as it needs `sap-btp-service-operator` one to be there as well, described in #330
- Putting `sap-btp-service-operator` in the operator's namespace won't pick it up as the operations already hard failed and won't be retried so it just stays there. (I'd assume that after the 10 hours it would retry the deletion but ci/cd can't wait that long)

In case of helm this should not happen as all custom CRDs will get uninstalled first then secrets, then namespaces last.
But in case helm is not used and we need to cleanup the entire namespace this is a problem as it never gets cleaned up unless some manual intervention is applied.

The only way to fix this now is to do step 3 above and issue a rollout restart for the operator's manager and hope it retries, which for me it did but may be highly dependent on the configured rotation ttl.

From what I understood k8s controllers can add a sort of retry delay when encountering a sync failure/impossibility to schedule a partial sync for the resource not wait for the full 10hours for the full loop to wake them, this retry logic would also fix #340

**Comment by kerenlahav** [comment]
The BTP operator cannot stop you from deleting a namespace since it does not own it. Once the namespace is marked for deletion, all resources inside it are also marked for deletion, secret is a simple resource without any finalizer, which means it will be deleted almost immediately (unlike ServiceInstance), there is nothing the BTP operator can do about it. 
You can block the secret from being deleted by adding it a finalizer, once all BTP resources are deleted you can remove the resources and the secret will be deleted.
I don't see how the "RequeueAfter" will solve this, can you explain?

**Comment by krodyrobi** [comment]
RequeueAfter would help when resource is stuck as the secret went away, it transitions to hard failure, after in the management namespace a new secret appears. Instead of transitionig to a hard failure and waiting for a full 10h it could retry to recover once every X minutes given the secret can be discovered at that time making the stable state reachable faster.

If the namespace is deleted the secret is gone - expected for it to get stuck, but could the finalizer be provided somehow by the operator? sorry rather new to k8s operators so it might be complete nonsense :) .

**Comment by kerenlahav** [comment]
In case of an error during "delete" operation the reconcile loop returns an error, k8s implements a "pull backoff" mechanism. next retry will occur a few seconds after the first, the gap between retries increases exponentially until it reaches the maximum time of 1 hour.

**Comment by krodyrobi** [comment]
Ok so it is a config the operator specifies [here](https://github.com/SAP/sap-btp-service-operator/blob/main/internal/config/config.go#L29) but not exposed, looked over and the numbers seem decent.

I think the best case of action here would be to document this behaviour (make it obvious - even if it is expected :) ), and provide guidance on how to fix it (mentioning the exponential expectation, or even restarting the service).
This could easily be avoided if secrets are in a managed namespace, or a clone is present there in the first place, plus it only really happens if helm is not used and manual deletion is triggered.

Btw, off topic: when is the next release be scheduled for?
