### ISSUE TITLE
Ability to add labels and annotations to generated secret

### ISSUE THREAD

**Issue by krodyrobi** [SAP/sap-btp-service-operator#333]
For instance [reflector](https://github.com/EmberStack/kubernetes-reflector)  and [reloader](https://github.com/stakater/Reloader) allow to configure what can get synched where and if it should be considered for their respective tasks.

Currently there is no way of configuring annotations/labels for the generated secret resources.

**Comment by TalShorSap** [comment]
What is the purpose of this configuration you want to do?

**Comment by krodyrobi** [comment]
Currently, a service instance can only be used for bindings within the owning namespace.
In our case each application is sandboxed within one namespace, but we would still be using the same logical btp subaccount.

Reloader would automatically restart deployments when the operator would rotate them, currently we can only restrict by namespace but cannot do it at a secret granularity as it is needs labels.

Reflector would be used to sync the bindings from the management namespace to the app namespace whatever that maybe.

namespace1: App1 + reflected-secret1
namespace2: App2 + reflected-secret2
management: ServiceInstance + ServiceBinding1 + ServiceBinding2 + secret1 (annotated) + secret2(annotated)

Instead of

namespace1: App1 + ServiceInstance + ServiceBinding1 + secret1 + operator-secret(btp-subaccount)
namespace2: App2 + ServiceInstance + ServiceBinding2 + secret2 + operator-secret(btp-subaccount)

Which would end up using 2 quotas for the service in BTP.

**Comment by TalShorSap** [comment]
In our new version (0.5.2) we allow the creation of the binding in different namespace, so please use that version.

**Comment by krodyrobi** [comment]
@TalShorSap Can you also add the new field in the documentation?
I'm assuming since secrets are namespace specific the binding should have the same pair of secrets as the instance namespace, correct?
As far as I can tell it did correctly create the resources.
