### ISSUE TITLE
Provide CRDs as a separate helm chart.

### ISSUE THREAD

**Issue by krodyrobi** [SAP/sap-btp-service-operator#337]
We are trying to do what method 2 in the docs describe, namely if we use the chart we cannot use operator `helm upgrade --install --dry-run` in conjuction with `kubectl --validate --dry-run` for our resources (ServiceInstances for example) as they don't exist.

[Helm documentation](https://helm.sh/docs/chart_best_practices/custom_resource_definitions/)
```The --dry-run flag of helm install and helm upgrade is not currently supported for CRDs. The purpose of "Dry Run" is to validate that the output of the chart will actually work if sent to the server. But CRDs are a modification of the server's behavior. Helm cannot install the CRD on a dry run, so the discovery client will not know about that Custom Resource (CR), and validation will fail. You can alternatively move the CRDs to their own chart or use helm template instead.```

I also tried using the chart as a subchart to have the above mentioned resources dry-run-able (using just the helm command of the parent) but the templates in the operator will always use the parent's `{.Release.namespace}`, which does not play well with the management namespace concept and least knowledge approach.

**Comment by krodyrobi** [comment]
We have an infra repository that sets up a k8s cluster installing  some helm charts for various cross cutting services, and it has 2 stages validate and apply.

During validate we install crds and apply either helm validate or kubctl validate for our configurations to make sure we have all the needed resources available and that the syntax is correct, no template problems etc. This cannot happen as we are forced to install/update the operator controllers before we are sure we are ok with using them (this is assuming CRDs are backward / forward compatible as k8s guidelines)

One approach which I saw cert-manager do is this [https://cert-manager.io/docs/installation/helm/#option-1-installing-crds-with-kubectl] as they have a value property to add or not the CRDs withing helm or externally.
Not sure which approach is better as I see this topic is "hot" in the community,

**Comment by loewenstein** [comment]
FWIW if nothing changed in Helm, then `helm upgrade` will actually not upgrade the CRDs in the `crds/` folder. That might be yet another reason to handle them separately.

**Comment by kerenlahav** [comment]
Please open a PR with the suggested change and we'll review it.
Thanks.

**Comment by krodyrobi** [comment]
The change is minimal. Have 1 value installCRDs: true by default then wrap the crd.yaml file in an if and then at release create an artifact in github with the file crd.yaml (not sure about the last part).

**Comment by krodyrobi** [comment]
Had a look and I don't see a way to tell kustomize to add non yaml constructs like helm ifs - then again I'm new to kustomize..

**Comment by krodyrobi** [comment]
I had a look, it feels weird that you guys are using 2 templating engines and I hope I understood the flow.
Feel free to edit as you see fit.
