### ISSUE TITLE
Can kube-rbac-proxy be removed from btp-service-operator?

### ISSUE THREAD

**Issue by lin1161** [SAP/sap-btp-service-operator#344]
Hello BTPSO Experts,  I would like to ask if btp-service-operator necessarily requires kube-rbac-proxy and is it possible for us to disable/remove it ?

**Comment by Austin926** [comment]
As a side note, it seems working as we tried some basic operations(create/update/delete service instances/binding) after removing the side-car container.

**Comment by TalShorSap** [comment]
Why you want to remove it?

**Comment by lin1161** [comment]
Hello @TalShorSap We’d like to deploy BTPSO into our product landscape, the quay.io/brancz/kube-rbac-proxy:v0.14.2 image failed for illegal docker registry check.  As @Austin926 mentioned, we tried to remove kube-rbac-proxy container from the deployment, the basic operations still work, so we'd like to check with your team, if this kube-rbac-proxy can be removed/disabled.

**Comment by kerenlahav** [comment]
removing the rbac proxy is not recommended since one of its roles is to ensure security and enforce rbac policies.
what is the issue with version 0.14.2?

**Comment by pre** [comment]
In our case we're getting the same question from the compliancy department - using a 3rd party container image behind a single person (`quay.io/brancz/`) raises eyebrows. 

Luckily the image source is configurable in values.yaml https://github.com/SAP/sap-btp-service-operator/blob/e4bc5f7d0722f80e8351940c65e91fc193bf5813/sapbtp-operator-charts/values.yaml#L33 

So it's possible to use the kube-rbac's container image "from a verified source".
