### ISSUE TITLE
Is it possible for BTPSO to import existing service instances?

### ISSUE THREAD

**Issue by smacl** [SAP/sap-btp-service-operator#356]
Is it possible to deploy a ServiceInstance CR that represents an already-existing instance in the target subaccount, and brings it under management of BTPSO? Currently, setting the "name" field to the name of an existing instance leaves the CR in a `CreateFailed` state with error "instance with same name exists for the current tenant" (full test CR below).

The intent is to handle use cases like the following:
- migrating from code-based or manual management to k8s-based management for existing instances that cannot easily be re-created or replaced (e.g., xsuaa, saas-registry)
- disaster recovery scenarios where clusters may be lost and re-created from backup, so new CRs are created

Thanks!

```
apiVersion: services.cloud.sap.com/v1
kind: ServiceInstance
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"services.cloud.sap.com/v1","kind":"ServiceInstance","metadata":{"annotations":{},"name":"auditlog-mgmt","namespace":"btp-adopt-provider-account"},"spec":{"serviceOfferingName":"auditlog-management","servicePlanName":"default","shared":true}}
  creationTimestamp: "2023-10-13T19:56:59Z"
  finalizers:
  - services.cloud.sap.com/sap-btp-finalizer
  generation: 1
  name: auditlog-mgmt
  namespace: btp-adopt-provider-account
  resourceVersion: "273862"
  uid: add642f1-2d7d-4bf9-b672-30940182d395
spec:
  externalName: auditlog-mgmt
  serviceOfferingName: auditlog-management
  servicePlanName: default
  shared: true
  userInfo:
    groups:
    - system:serviceaccounts
    - system:serviceaccounts:default
    - system:authenticated
    uid: ac8234b2-9151-4794-8714-8f99158993b7
    username: (redact)
status:
  conditions:
  - lastTransitionTime: "2023-10-13T19:56:59Z"
    message: 'ServiceInstance create failed: instance with same name exists for the
      current tenant'
    observedGeneration: 1
    reason: CreateFailed
    status: "False"
    type: Succeeded
  - lastTransitionTime: "2023-10-13T19:56:59Z"
    message: ""
    observedGeneration: 1
    reason: NotProvisioned
    status: "False"
    type: Ready
  - lastTransitionTime: "2023-10-13T19:56:59Z"
    message: 'ServiceInstance create failed: instance with same name exists for the
      current tenant'
    observedGeneration: 1
    reason: CreateFailed
    status: "True"
    type: Failed
  hashedSpec: 4490a7d878dba14961c5057cca1eddb6
  observedGeneration: 1
  ready: "False"
```

**Comment by kerenlahav** [comment]
If I understand your question, you are referring to instance recovery.
recovery of an instance is possible when you are creating an instance with the same name, in the same namespace and in the same cluster id as the original instance, if one of these parameters does not match the operator will try to create a new instance and won't recover an existing one.
The error you see is returned from the broker itself as a response to the "create" request since the operator did not find an instance that matches the parameters you provided.

**Comment by smacl** [comment]
Thanks @kerenlahav!
There are two use cases I am wondering about, in the context of migrating an existing deployment from code/clickops to k8s:
1. "Importing" an instance that already exists in BTP, which was not provisioned through BTPSO
2. "Recovering" an instance for which there was already a CR (which may have originally been provisioned through BTPSO or not)

For 1 - I gather this is not possible today? Is it possible to add it so that existing instances created through e.g. Service Manager API can be managed through BTPSO instead?

For 2 - thanks for the details! What determines the cluster ID? If a K8S cluster is lost and re-created with a new BTPSO deployment (but using the same SM service key), would the cluster ID be the same, allowing instance recovery? What if the SM service key was also re-created but the instances to be recovered still exist?

**Comment by kerenlahav** [comment]
1. importing instances is not supported in general since you cannot change the platform of the instance (CF to k8s for example), not all brokers support UPDATE of an instance, therefore it will not be possible to "move" it to another platform.
2. the cluster id is a random uuid created during the installation, you can specify the cluster id as a parameter.
if you reinstall without specifying the cluster id it will get a new id so instances won't be able to recover, but instances contain the cluster id in their context so you can retrieve from it

**Comment by smacl** [comment]
Hi @kerenlahav, thanks very much for the details in your earlier comment.

I had a chance to try this and it did not work, maybe I am still missing something.

I created a service instance using BTPSO:
![image](https://github.com/SAP/sap-btp-service-operator/assets/77069312/b402d8cd-71f3-42d7-8b77-be6c99646fa3)

I then backed up the CR, deployed a new K8S cluster using the same cluster ID, and restored the CR.
```
$ k -n sap-btp-operator get cm -o yaml sap-btp-operator-config
apiVersion: v1
data:
  ALLOW_CLUSTER_ACCESS: "true"
  CLUSTER_ID: bdf59a6b-a72f-4737-ad0d-edd71c242084
  MANAGEMENT_NAMESPACE: sap-btp-operator
  RELEASE_NAMESPACE: sap-btp-operator
kind: ConfigMap
metadata:
  creationTimestamp: "2023-11-02T20:07:11Z"
  name: sap-btp-operator-config
  namespace: sap-btp-operator
  resourceVersion: "13594"
  uid: 45a2df0a-f06b-4f44-bd3b-fc842918e277

$ k -n btp-provider-account get serviceinstance auditlog -o yaml
apiVersion: services.cloud.sap.com/v1
kind: ServiceInstance
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"services.cloud.sap.com/v1","kind":"ServiceInstance","metadata":{"annotations":{},"name":"auditlog","namespace":"btp-provider-account"},"spec":{"serviceOfferingName":"auditlog","servicePlanName":"oauth2"}}
  creationTimestamp: "2023-11-02T23:51:14Z"
  finalizers:
  - services.cloud.sap.com/sap-btp-finalizer
  generation: 1
  name: auditlog
  namespace: btp-provider-account
  resourceVersion: "166372"
  uid: 0545683b-76b6-4349-94e2-01f7908b84b8
spec:
  externalName: auditlog
  serviceOfferingName: auditlog
  servicePlanName: oauth2
  userInfo:
    groups:
    - system:serviceaccounts
    - system:serviceaccounts:default
    - system:authenticated
    uid: **
    username: **
status:
  conditions:
  - lastTransitionTime: "2023-11-02T23:51:14Z"
    message: 'ServiceInstance create failed: instance with same name exists for the
      current tenant'
    observedGeneration: 1
    reason: CreateFailed
    status: "False"
    type: Succeeded
  - lastTransitionTime: "2023-11-02T23:51:14Z"
    message: ""
    observedGeneration: 1
    reason: NotProvisioned
    status: "False"
    type: Ready
  - lastTransitionTime: "2023-11-02T23:51:15Z"
    message: 'ServiceInstance create failed: instance with same name exists for the
      current tenant'
    observedGeneration: 1
    reason: CreateFailed
    status: "True"
    type: Failed
  hashedSpec: 13ae9f5c73254e23281a102fea3c8265
  observedGeneration: 1
  ready: "False"
```

From the CR status, it looks like BTPSO tried to re-create the instance rather than assuming control of the existing one.

Appreciate any suggestions you have. Thanks!

**Comment by kerenlahav** [comment]
Hi,
Please open NGPBUG (Service Manager component) with the above details and include the subaccount id and landscape so i'll be able to check it

**Comment by smacl** [comment]
Thank you @kerenlahav. Unfortunately I've deleted that subaccount - will open an NGPBUG when I have another repro.
