### ISSUE TITLE
Improve the quality of PR reviews by paying attention to the PR human readable content.

### ISSUE THREAD

**Issue by pre** [SAP/sap-btp-service-operator#357]
Pull requests should either conform to the Pull Request template or the PR template should be removed it altogether.

In short - some kind of quality standard should be established on how a PR description should look like. 

For example changelog for v0.3.9 links to two pull requests #248 and #250. 
* https://github.com/SAP/sap-btp-service-operator/releases/tag/v0.3.9

Both Pull Requests have a long wall of text, but that text is the pull request template's non-replaced content as is. 

The sap-btp-service-operator is a core component. Paying attention to the quality of pull requests review should include requesting the pull request's human readable content be relevant. 

Another option would be to remove the pull request template altogether and not spam the PR contents with the template placeholder content. 

Further examples or PRs which have the descirption with the PR template as is (spam) or no content at all:
* https://github.com/SAP/sap-btp-service-operator/pull/349
* https://github.com/SAP/sap-btp-service-operator/pull/350
* https://github.com/SAP/sap-btp-service-operator/pull/347
* https://github.com/SAP/sap-btp-service-operator/pull/352
* https://github.com/SAP/sap-btp-service-operator/pull/343
* https://github.com/SAP/sap-btp-service-operator/pull/342

![image](https://github.com/SAP/sap-btp-service-operator/assets/63895/7a2e5308-8c7b-4c59-9f3a-36115c05f4ac)

![image](https://github.com/SAP/sap-btp-service-operator/assets/63895/d9e8b4d5-4664-496b-a74b-73e78189f1ad)

**Comment by kerenlahav** [comment]
You're absolutely right, we'll make sure to improve it
