### ISSUE TITLE
Upgrade golang runtime version

### ISSUE THREAD

**Issue by idogoren** [SAP/sap-btp-service-operator#370]
Hi,

We're consuming this chart for our purposes and as part of that, we use BDBA for performing security scans.
The issues which were detected are related to go 1.21 which you are using but go has released verison1.21.4.
Could you please upgrade your Dockerfile accordingly and create a new verison?

Thanks.

![image](https://github.com/SAP/sap-btp-service-operator/assets/13237243/52bc69dc-33f3-4153-9067-130e674c2791)

**Comment by kerenlahav** [comment]
fixed in 
https://github.com/SAP/sap-btp-service-operator/releases/tag/v0.5.6
Thanks
