### ISSUE TITLE
CVE vulnerabilities found for kube-rbac-proxy v14.0.2

### ISSUE THREAD

**Issue by lin1161** [SAP/sap-btp-service-operator#380]
Hi, 
I saw you already updated golang-runtime version to 1.21.4 for btp-service-operator image in release v0.5.6, but the golang-runtime in  kube-rbac-proxy image is still 1.20.4, do you have a plan to upgrade it? 
Protecode scan reports the vulnerabilities for kube-rbac-proxy image:
![image](https://github.com/SAP/sap-btp-service-operator/assets/40016856/b2abdfb8-0995-4891-81c5-1027494f0014)

**Comment by kerenlahav** [comment]
Hi @lin1161, the kube-rbac-proxy is an external image, i'll update it in the next release but you don't need to wait for it, you can configure the version in the [values.yaml](https://github.com/SAP/sap-btp-service-operator/blob/main/sapbtp-operator-charts/values.yaml#L34)

**Comment by lin1161** [comment]
Hello @kerenlahav , seems kube-rbac-proxy v15.0 still use golang 1.20, I've opend an issue for them https://github.com/brancz/kube-rbac-proxy/issues/274
