### ISSUE TITLE
Readme is unclear about compatibility of previous "multitenancy" and new "Working with Multiple Subaccounts" approach

### ISSUE THREAD

**Issue by benzni** [SAP/sap-btp-service-operator#396]
Since the update of the Readme with PR: https://github.com/SAP/sap-btp-service-operator/pull/392, the documentation is inconclusive about the compatibility of the new approach of working with multiple subaccounts within the same cluster, compared to what was outlined in: [b83f523/Readme.md#default-access-credentials](https://github.com/SAP/sap-btp-service-operator/tree/b83f523f8d45b1484d79e84b156e6443e18e6535?tab=readme-ov-file#default-access-credentials)

Namely if the following still works:
> Define a secret named `sap-btp-service-operator` in the namespace. `ServiceInstance` and `ServiceBinding` that are applied in the namespace will belong to the subaccount from which the credentials were issued. 

Also if it still works (which I hope) the section [Secrets presedence](https://github.com/SAP/sap-btp-service-operator/blob/main/README.md#secrets-presedence) also needs to be updated to define the order the secrets will be applied

**Comment by I065450** [comment]
Hi @benzni 

This functionality is still working and we are still in the process of restructuring the README. 
Please be aware that if you define an explicit secret, it will take over the namespace secret.

Regards,
Naama
