### ISSUE TITLE
create btp kafka by btp operate in  canary https://canary.cockpit.btp.int.sap/

### ISSUE THREAD

**Issue by minggongcheng** [SAP/sap-btp-service-operator#402]
ENV:  BTP canary.  https://canary.cockpit.btp.int.sap/

Error:
Message:               BrokerError:PublicEndpointsNotSupported, Status: 400, Description: Public endpoints for clusters are not yet supported in this landscape

the Yaml file:
apiVersion: services.cloud.sap.com/v1
kind: ServiceInstance
metadata:
  name: canary-kafka
  namespace: kafka
spec:
  serviceOfferingName: kafka
  servicePlanName: standard
  externalName: canary-kafka
  parameters:
    public_ip: true
    allow_access: "x.x.x.x"

**Comment by kerenlahav** [comment]
Hi @minggongcheng 
From the error message it seems like what you are trying to do is not supported, anyway this error is returned from the kafka broker and is not related to the BTP operator, please consult with the kafka team.
Thanks
