### ISSUE TITLE
Controller Manager fails to start on GKE

### ISSUE THREAD

**Issue by SvendDomdey** [SAP/sap-btp-service-operator#403]
Hi,

we are trying to set up the SAP BTP Service Operator on our Kubernetes Cluster on GKE. The cluster was created with default settings.

We were trying follow the instructions in the Setup part of  your README (https://github.com/SAP/sap-btp-service-operator?tab=readme-ov-file#setup) step by step but unfortunately ran into issues.

What we did (after freshly creating the cluster):
- Install `cert-manager`. We followed the steps described on https://cert-manager.io/docs/installation/helm/#steps
```
helm repo update
helm repo add jetstack https://charts.jetstack.io --force-update 
helm install \
  cert-manager jetstack/cert-manager \
  --namespace cert-manager \
  --create-namespace \
  --version v1.14.3 \
  --set installCRDs=true
```

- Create a Service Manager instance on BTP with plan `service-operator-access` and create a service binding to it.
- Add the repo (step 3 in your guide)
- Install the service operator
```
helm upgrade --install sap-btp-operator-1 sap-btp-operator/sap-btp-operator \
    --create-namespace \
    --namespace=sap-btp-operator \
    --set manager.secret.clientid=<clientid> \
    --set manager.secret.clientsecret=<clientsecret> \
    --set manager.secret.sm_url=<sm_url> \
    --set manager.secret.tokenurl=<auth_url>
```
where we replaced the values with those from the binding.

Output of this command (retry):
```
W0229 15:20:55.769973    7644 warnings.go:70] autopilot-default-resources-mutator:Autopilot updated Deployment sap-btp-operator/sap-btp-operator-controller-manager: defaulted unspecified resources for containers [kube-rbac-proxy] (see http://g.co/gke/autopilot-defaults), and adjusted resources to meet requirements for containers [manager] (see http://g.co/gke/autopilot-resources)
Release "sap-btp-operator" has been upgraded. Happy Helming!
NAME: sap-btp-operator
LAST DEPLOYED: Thu Feb 29 15:20:52 2024
NAMESPACE: sap-btp-operator
STATUS: deployed
REVISION: 3
TEST SUITE: None
```

The issue we experience:
- The BTP service operator controller pod is stuck in "container_creating"
![image](https://github.com/SAP/sap-btp-service-operator/assets/75790355/0859c8c8-ed27-4656-9b8c-025ee19b98c1)
![image](https://github.com/SAP/sap-btp-service-operator/assets/75790355/1e0dbdb5-65f5-412f-91be-f99bc32d4953)

- The error reprting on Google Cloud console says
![image](https://github.com/SAP/sap-btp-service-operator/assets/75790355/2742adbb-ad35-493b-a95d-eb8ed51b5da9)
so we are suspecting something is wrong with the setup around `cert-manager`. There were no errors during installation though. Also the pods in the cert-manager namespace look healthy.
![image](https://github.com/SAP/sap-btp-service-operator/assets/75790355/f7c81309-34ad-44d3-b4ea-ea6c5ba6cc6b)

As we were trying to follow your documentation, it would be great if you could help us out here. Is there something wrong with the steps that we did for installing `cert-manager`?

Thanks for your support!

**Comment by kerenlahav** [comment]
Hi @SvendDomdey 
The error message indicates you are missing a secret that is created by cert manager, check the status of a certificate named "sap-btp-operator-serving-cert" to see why the secret is not created.
Thanks

**Comment by kerenlahav** [comment]
if issue still occurs please reopen
