### ISSUE TITLE
Refresh Service binding when service instance is updated.

### ISSUE THREAD

**Issue by k-brady-sap** [SAP/sap-btp-service-operator#404]
Requirement
When a Service instance is updated - e.g. BTP message queue is updated to remove connection protocol.  Can the linked service binding be updated at the same time?

The credentialsRotationPolicy can only run on a set time and is also limited by the control loop of the cluster so there is no guarentee when the service binding is updated.

Is there any best practice on how to update service bindings when a service instance is updated?

**Comment by kerenlahav** [comment]
Hi @k-brady-sap 
binding does not support "update" operation, if an instance is updated you need to create a new binding.

**Comment by k-brady-sap** [comment]
ok - so as part of a service-instance update, the update script would need to explicitly delete the existing service-binding, then update the service instance, and finally create a service-binding?

**Comment by kerenlahav** [comment]
it depends on the broker, old bindings can be valid even if the instance is updated, and if this is the case you don't have to delete the binding before the instance is updated.
if you want to keep the same name then yes, you have to delete the old one before creating a new one.
