### ISSUE TITLE
Support non-dev mode for btp operator log

### ISSUE THREAD

**Issue by gadisn** [SAP/sap-btp-service-operator#405]
The manager should support non-dev mode for the the log.

Today dev mode is hard coded to true [here](https://github.com/SAP/sap-btp-service-operator/blob/main/main.go#L75C29-L75C39).

The logger lib dev mode setting can be seen [here](https://github.com/kubernetes-sigs/controller-runtime/blob/v0.14.2/pkg/log/zap/zap.go#L52C6-L52C16) and [here](https://github.com/kubernetes-sigs/controller-runtime/blob/v0.14.2/pkg/log/zap/zap.go#L136).

In dev mode a [console encoder](https://pkg.go.dev/go.uber.org/zap/zapcore#NewConsoleEncoder) is used, while in non-dev mode a [json encoder](https://pkg.go.dev/go.uber.org/zap/zapcore#NewJSONEncoder) is used.

**Comment by kerenlahav** [comment]
will be part of the next release (~next week)
