### ISSUE TITLE
So many servicebindings are in CreateInProgress state

### ISSUE THREAD

**Issue by krimeshshah** [SAP/sap-btp-service-operator#417]
Hi Team,

We recently observed that, so many ServiceBindings are in CreateInProgress state for specific one gardener cluster. There are servicebindings with a name that is rather unique, which already exist in. btp, they were most certainly created by btp-operator, yet btp operator claims that it can not create these bindings as they already exist (it looks like it created them but “forgot” that it did) 

Can you help us fix the issue permanently? And Also can you provide us the root cause of the issue?

Regards,
Krimesh

**Comment by krimeshshah** [comment]
<img width="621" alt="image" src="https://github.com/SAP/sap-btp-service-operator/assets/8235831/ab50f06b-e350-4b08-8575-2680c935990e">

**Comment by I065450** [comment]
Hi @krimeshshah 

It seems that the issue might be related to credential rotation. Could you please try updating to the latest version?

If the problem persists, please share the YAML for the binding with us so that we can conduct further investigation.

Thanks,
Naama

**Comment by krimeshshah** [comment]
HI @I065450 ,

We are already on the latest btp-operator chart version v0.6.1. We believe its possible that this issue occurred during the olderversions as the servicebindings are in CreateInProgress state since more than a months. In this case now we have to delete old bindings from BTP  specific to acc cluster. Can you help us doing that considering there are many servicebinding in createInprogress state.

Regards,
krimesh

**Comment by I065450** [comment]
You are correct, it seems there may have been an issue that has been resolved. 

Could you please share the YAML for both the binding and the binding with the error so that we can conduct further investigation? 

Thanks,
Naama

**Comment by I065450** [comment]
Changing the cluster ID caused the issue.
It is not supported to change the cluster id after operator setup.
