### ISSUE TITLE
ServiceBindings in CreateInPrgress state deleted from k8s cluster but doesnt reflect the same deleting in btp-cockpit

### ISSUE THREAD

**Issue by krimeshshah** [SAP/sap-btp-service-operator#426]
Hi Team,

Following this issue (https://github.com/SAP/sap-btp-service-operator/issues/417) we faced few weeks back, we tried reproduce the scenario in our test cluster.

Test Scenario1.
1. Created xsuaa service instance with exsiting clusterid in btp-operator
2. Changed the cluster id
3.  Created service binding successfully (created with running state)
4. Triggered credential rotation to trigger service binding rotation
5.  Newly created service binding was in Updated and ready state

Test Scenario 2:
From Test Scenario 1, step 1 to 3 performed as it is
2. Changed the cluster ID again after creation of servicebinding
3.  Triggered the credential rotation
4.  Which caused newly created service binding in CreateInProgress state

Observation and a problem here was, even though the service binding was in CreateInProgress state in k8s cluster, the corresponding service binding in btp-cockpit was in running state. Also when we deleted the ServiceBinding from k8s cluster, it did not reflect and delete it in btp-cockpit.
Can you please check and provide solution to this.

**Comment by kerenlahav** [comment]
Hi @krimeshshah 
Changing the cluster id is not a valid use case and is not supported, a cluster id validation was added in release v0.6.2, in case changed the operator will not be able to start
please use the latest version.
Thanks

**Comment by kerenlahav** [comment]
closing since there is no comment, please reopen in case needed
