### ISSUE TITLE
Error in cert-manage-webhook configurations

### ISSUE THREAD

**Issue by saud89** [SAP/sap-btp-service-operator#429]
Hi, 

After installing cert-manager and sap-btp-operator on Gardener clusters, we see errors in the webhook configuration from Gardener. The errors are on Maintenance and Hibernation preconditions, please find the screenshots below. 
<img width="1218" alt="Screenshot 2024-05-07 at 10 04 07 AM" src="https://github.com/SAP/sap-btp-service-operator/assets/20837274/2dd5cb9a-d3f7-4650-8dd2-0704680b6fb9">
<img width="1218" alt="Screenshot 2024-05-07 at 10 10 38 AM" src="https://github.com/SAP/sap-btp-service-operator/assets/20837274/1bf0970f-7eb2-4e52-b91c-f4d84e169dba">

Can you please help, how to avoid these errors?

Thanks and regards,
Saud

**Comment by I065450** [comment]
Hi @saud89 

Were you able to successfully install cert manager? if not please try to reinstall cert manager.
anyway it doesn't seem like an issue with sap-btp-operator, successful installation of a cert manager is a prerequisite.

Regards,
Naama
