### ISSUE TITLE
Caching All Secrets

### ISSUE THREAD

**Issue by ralikio** [SAP/sap-btp-service-operator#432]
Most recently, we have discovered an issue with sap-btp-service-operator's controller-runtime manager. Managers work based on caches not to overwhelm K8S api. If sap-btp-service-operator works on a cluster with numerous secrets and lots of `data` fields then the cache goes beyond our 200Mi and we get OOM error on a `manager` container. SAP BTP Service Operator should only watch secrets that it created. Please implement selective caching that limits cache consumption to only keep necessary secrets there. Please take a look at implementation [CacheCreator](https://github.com/kyma-project/btp-manager/blob/5c44cc4fa16961c24c34b4ff376735c64504dee0/controllers/cache.go#L14) used in [BTP Manager's managers](https://github.com/kyma-project/btp-manager/blob/5c44cc4fa16961c24c34b4ff376735c64504dee0/main.go#L93).

**Comment by kerenlahav** [comment]
Hi @ralikio 
thank you for the information, how did you migrate existing secrets that dont have the needed label?

**Comment by ralikio** [comment]
Hello @kerenlahav, we have a central component that manages the secrets so they had the correct label in the first place. The main problem that we have is wit secrets created with helm. They have distinctive type `helm.sh/release.v1` so filtering those would be the simplest solution. Better bulletproff solution would be for you figure out the secrets by instances that they were created from.

**Comment by kerenlahav** [comment]
Thanks @ralikio 
it is not an easy task to figure out the secrets since there is no naming convension or any common ground, so i think will do it configurable and disabled by default
