### ISSUE TITLE
Failed to create service instance

### ISSUE THREAD

**Issue by ww917352** [SAP/sap-btp-service-operator#433]
Dear colleagues,

We are trying to create AI Core service instances via BTP operator on eu10 production. The creation failed, and I could see the following error message in the live manifest of the `serviceinstance`:

```
error sending request GET /v1/service_instances: Get
        "<<...encrypted_string...>>/v1/service_instances?attach_last_operations=true&fieldQuery=name+eq+%27ai-core%27+and+context%2Fclusterid+eq+%27B9F82677-D4A8-6153-847D-B291568D6256%27+and+context%2Fnamespace+eq+%27ai-core-namespace%27&labelQuery=_k8sname+eq+%27aicore-service-instance%27":
        Post
        "<<....encrypted_string....>>/oauth/token":
        unsupported protocol scheme ""
```

Can you please help me? Thank you!

If you want to check the encrypted strings in the above message, please contact me via Slack.

Cheers,
Wei

**Comment by ww917352** [comment]
I will close this ticket for now. I am more convinced now it is an AI Core issue.

**Comment by kerenlahav** [comment]
Hi @ww917352 
Seems like an issue with the operator's credentials, verify that service manager url and token url are correct.
Thanks,
Keren
