### ISSUE TITLE
Credential rotation policy not working as expected in my setup

### ISSUE THREAD

**Issue by mbakr1** [SAP/sap-btp-service-operator#438]
I am trying to have Credential rotation policy setup in my integration with my BTP instance but for some reason I am not seeing any effect with changes I added following the guide. 
Here is an example for my service-binding.yaml 
`apiVersion: services.cloud.sap.com/v1
kind: ServiceBinding
metadata:
  name: obs-dev-service-binding
  namespace: sap-btp-operator
spec:
  serviceInstanceName: ocas-dev-test6
  secretName: sap-btp-service-operator-sb
  credentialsRotationPolicy:
    enabled: true
    rotatedBindingTTL: 1h
    rotationFrequency: 1h`
ID: 51639a3c-bf92-4260-8fbf-8ffda0b94fdc

**Comment by I065450** [comment]
Hi @mbakr1 

You don't see any rotation? Did you wait for a full reconciliation? please check the Last Credentials Rotation Time on the binding.

Regards,
Naama

**Comment by mbakr1** [comment]
yea I saw no rotation. yea I waited and the last creds created was 52 days ago and its expired certificate

**Comment by I065450** [comment]
please share the full YAML for the binding with us so that we can conduct further investigation.

**Comment by I065450** [comment]
The operator access binding has an invalid certificate, causing the connection to BTP to fail.
