### ISSUE TITLE
Missing Managed by Label

### ISSUE THREAD

**Issue by ralikio** [SAP/sap-btp-service-operator#443]
`services.cloud.sap.com/managed-by-sap-btp-operator` label is not applied to service instances and service bindings. Because of that the limited cache functionality introduced in https://github.com/SAP/sap-btp-service-operator/pull/435 is not going to cache service instances and service bindings.

**Comment by kerenlahav** [comment]
Label is not needed, all btp operator service instances and binding will be added to the cache
