### ISSUE TITLE
Metrics endpoint for btp operator

### ISSUE THREAD

**Issue by yemramirezca** [SAP/sap-btp-service-operator#444]
Hi, 
The k8s service sap-btp-operator-controller-manager-metrics-service uses https, 
how could I see the exposed metrics on the /metric endpoint?

is there a list of metrics documented somewhere?
Thanks

**Comment by kerenlahav** [comment]
The BTP operator is built with kubebuilder, the metrics service is included by default, to use it you need to install prometheus and enable it,
follow the instructions in [kubebuilder book](https://book.kubebuilder.io/reference/metrics.html)
