### ISSUE TITLE
Does subaccount-for-a-namespace still supports the secret in the namespaces or these secrets must go to the management namespace?

### ISSUE THREAD

**Issue by ptesny** [SAP/sap-btp-service-operator#448]
Does [subaccount-for-a-namespace](https://github.com/SAP/sap-btp-service-operator?tab=readme-ov-file#subaccount-for-a-namespace) still supports the secret in the namespaces or these secrets must go to the management namespace?

This still worked as expected with the previous version of the operator. 

Just assume the following scenario:
there is hundreds of namespace where one single secret is required. According to the documentation I'd have to create a hundred of secrets, all identical but the secret name prefixed with the name of a namespace.

**Comment by I065450** [comment]
Hi @ptesny 

You can still use secret in the namespaces.

Best Regards,
Naama
