### ISSUE TITLE
bug in helm chart + add support for pod affinity

### ISSUE THREAD

**Issue by yyardeng** [SAP/sap-btp-service-operator#459]
version 0.6.5 of the operator helm chart has a bug in the deployment template where the variable checked in the if condition for the node selector and tolerations is not the value that is used in the template:

```
      {{- if .Values.manager.nodeSelector }}
      nodeSelector: {{ toYaml .Values.deployment.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if .Values.manager.tolerations }}
      tolerations: {{ toYaml .Values.deployment.tolerations | nindent 8 }}
      {{- end }}
```

which means the values have to be set twice in the values file for the configuration to take effect.

in addition, it would be great if support for configuring affinity in the deployment could be added.
perhaps something like:

```
      {{- with .Values.manager.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
```

adding support for topologySpreadConstraints instead or in addition to affinity would be helpful as well.

**Comment by I065450** [comment]
Hi @yyardeng 

Please review PR: https://github.com/SAP/sap-btp-service-operator/pull/460 if it meets your request.

Regards,
Naama

**Comment by yyardeng** [comment]
@I065450 yes, thank you - it would be great to get support for topology spread constraints as well since that feature is better for high availability purposes (GA since 1.19, in case this is relevant). it would be something like:

```
      {{- with .Values.manager.topologySpreadConstraints }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
```

**Comment by I065450** [comment]
fixed in PR: https://github.com/SAP/sap-btp-service-operator/pull/460
