### ISSUE TITLE
Label rotated binding secrets

### ISSUE THREAD

**Issue by ofirmad** [SAP/sap-btp-service-operator#461]
When binding gets rotates, a new secret with the old cred' is being created and live for defined TTL time.
We monitor when the cred' are expired, but would like to monitor only the active cred' secret (not the rotated, even though it's exists).

Could you add a label to the rotated secret so we can exclude it from our side?
If so, I would also like to understand how much time do you think it will take for this feature request.

Thanks.

**Comment by I065450** [comment]
Hi @ofirmad 

Perhaps you can filter out all secrets that have a hyphen in their names.
A feature request should be evaluated and prioritized by our PO, Avi Lupu.

Regards,
Naama

**Comment by ofirmad** [comment]
Hyphen names are problematic as we already have hyphen in our secrets.

**Comment by I065450** [comment]
Alright, you’ll still have the same secret name with a suffix (e.g., _*). 
You might be able to apply some logic to handle it effectively...

However, if you’d still like to request a feature, you can do so here:
[https://sap.sharepoint.com/sites/201434/SitePages/BTP-Cloud-Fundamental-Services-requirements-process.aspx]
