### ISSUE TITLE
Secret/sap-btp-operator-clusterid INITIAL_CLUSTER_ID is misleading

### ISSUE THREAD

**Issue by pre** [SAP/sap-btp-service-operator#468]
Nowdays sap-btp-service-operator creates an adhoc cluster id, if one wasn't provided. This value is stored in Secret/sap-btp-operator-clusterid INITIAL_CLUSTER_ID and gives the impression that this is something initial.

However, if the cluster id WAS defined - that cluster id is also in `INITIAL_CLUSTER_ID` even though it's the actual cluster id - not "initial".

As a result, the value is in two places now:
* `Secret/sap-btp-operator-clusterid > INITIAL_CLUSTER_ID`
* `ConfigMap/sap-btp-operator-config > CLUSTER_ID` 

Having the value existing in two places is a source of confusion.

**Comment by I065450** [comment]
Hi @pre 

We store the same value under two keys to ensure that the cluster ID remains unchanged during operator updates. This resolves issues previously experienced by customers where the cluster ID changed after an update, leading to content mismatches.

Best regards,
Naama

**Comment by pre** [comment]
OK
