### ISSUE TITLE
Redundant error log thrown when an optional subaccount secret does not exist

### ISSUE THREAD

**Issue by szwedm** [SAP/sap-btp-service-operator#469]
The following error is visible in the controller logs even when only the default secret should be used for service instances management: https://github.com/SAP/sap-btp-service-operator/blob/765f5e553ce6b5a6ff39fbeb6d9d018a7e958809/internal/utils/secret_resolver.go#L67.
The error is ignored later: https://github.com/SAP/sap-btp-service-operator/blob/765f5e553ce6b5a6ff39fbeb6d9d018a7e958809/internal/utils/secret_resolver.go#L97
and the controller picks the default secret for further operations.

**Comment by I065450** [comment]
I will change the log level to info.

**Comment by I065450** [comment]
https://github.com/SAP/sap-btp-service-operator/pull/470
