### ISSUE TITLE
Error with service binding

### ISSUE THREAD

**Issue by i053322** [SAP/sap-btp-service-operator#472]
Hi,

We are using BTP Operator version 0.6.1 in Business Application Studio. I noticed some errors in the BTP Operator pods. The error is: "Binding with the same name exists for instance with ID 7b426751-d968-4ae5-8c6e-3916e7948691." This occurs with multiple service bindings that have generated suffixes. The status of the service binding is "CreateInProgress," and "Ready" is set to false.

We upgraded to version 0.6.8, but we still see the same error.

Regards,
Yossi

**Comment by kerenlahav** [comment]
Hi Yossi,
Do you see the binding in the cockpit/btpcli?
can you please verify the k8sname, namespace and cluster id matches the details in the cluster?
which landscape is it?
please attach the binding's yaml

**Comment by i053322** [comment]
it is in all our landscape canary/prod.
It is for all the binding yaml 
yes i can see it in the cockpit  - https://emea.cockpit.btp.cloud.sap/cockpit/#/globalaccount/25656850-f8d3-4ba3-a5f0-472720ec6ce2/subaccount/04561948-7742-4409-b28e-39ea0e5f5ea7/service-instances&//detail/7b426751-d968-4ae5-8c6e-3916e7948691/?layout=TwoColumnsMidExpanded
This is the service binding https://github.wdf.sap.corp/app-studio/logging-pre-chart/blob/master/logging-pre/templates/service-binding.yaml
apiVersion: services.cloud.sap.com/v1
kind: ServiceBinding
metadata:
  name: cloud-logging
  namespace: logging
  labels:
    app.kubernetes.io/instance: logging-pre
spec:
  credentialsRotationPolicy:
    enabled: true
    rotatedBindingTTL: 168h
    rotationFrequency: 336h
  externalName: cloud-logging
  secretName: cloud-logging-standard-creds
  serviceInstanceName: cloud-logging
 

this example is BR10

**Comment by i053322** [comment]
yes we are using argoCD , I saw this change and i think it cause us issues in the new versions and the POD didn't started because different in the clusterID. i saw that we have sceret sap-btp-operator-clusterid and config map
sap-btp-operator-config with clusterID. do I need to add more changes for the upgrade to 0.6.8 ? how do I need to get the clusterid ?

**Comment by kerenlahav** [comment]
the cluster id is part of the context of each instance/binding, the problem now is that you have many resources, each one with different cluster id, this will result in cred rotation and recovery issues for existing instances/bindings, there is nothing to do for existing resources.
From now on set a constant cluster id, once done, if the operator fails to start delete the sap-btp-operator-clusterid secret and restart.

**Comment by i053322** [comment]
After the upgrade I saw error in the pod because the cluster id , and i saw that the value in the config map and the secret are different. in your logic you just create a dummy uuid and set it https://github.com/SAP/sap-btp-service-operator/blob/765f5e553ce6b5a6ff39fbeb6d9d018a7e958809/hack/setup_operator_env.sh#L37 
so do I need to do the same and set the clusterid and change the value in https://github.com/SAP/sap-btp-service-operator/blob/main/sapbtp-operator-charts/values.yaml#L91  

This is the error :
2024-10-08T06:32:50Z	INFO	setup	Allowed namespaces are [logging bas webide-system]
panic: ClusterID changed, which is not supported. Please redeploy with --set cluster.id=271c8716-2699-4757-a355-5f500333e018

goroutine 1 [running]:
main.main()
	/workspace/main.go:140 +0x1d65

**Comment by kerenlahav** [comment]
since you are using argo, you need to set the cluster id with some constant value (--set cluster.id=XXXX) and not let the operator generate it for you.
once you set it, delete the secret i mentioned and restart the pod

**Comment by i053322** [comment]
is it ok to provide the cluster technical id: for example shoot--ci-aws--stg-aws-10 ?

**Comment by kerenlahav** [comment]
yes, max length is 37 characters and don't use special chreacters ($#*...)

**Comment by I065450** [comment]
you cab view using btp cli: https://help.sap.com/docs/btp/btp-cli-command-reference/btp-get-services-binding
or Service Manager operation API https://api.sap.com/api/APIServiceManager/resource/Service_Instances
