### ISSUE TITLE
Getting namespace from spec instead of metadata

### ISSUE THREAD

**Issue by althaf1088** [SAP/sap-btp-service-operator#473]
Hi Team,

We are using sap-btp-service-operator with Crossplane, to take advantage of the secret rotation functionality provided by the operator following the documentation [here](https://pages.github.tools.sap/cloud-orchestration/docs/sap-services/btp-services/service-managment/multiple-subaccounts#create-serviceinstance-for-sub-b)

Due to Crossplane design for Composition, we cannot add metadata.namespace since it is not designed to support namespace scoped resources.[Crossplane namespace issue](https://github.com/crossplane/crossplane-runtime/pull/541)

So would like to check if its feasible to get the namespace either from metadata or from spec.forprovider like [(code)](https://github.com/SAP/sap-btp-service-operator/blob/765f5e553ce6b5a6ff39fbeb6d9d018a7e958809/controllers/serviceinstance_controller.go#L175) for other provider mentioned [here](https://pages.github.tools.sap/cloud-orchestration/docs/sap-services/gardener/shoot) 

This will help us to avoid any workaround and also to fully use the functionalities of crossplane .

**Comment by thonacker** [comment]
@kerenlahav Can you help here? This would be very helpful for us moving forward with Crossplane as orchestration tool

**Comment by kerenlahav** [comment]
Hi, 
I dont undertand the request, how are you working with the operator? the operator reacts to CRs, where are you creating the CRs? how the CR looks like? please share as much details as possible.

Thanks.

**Comment by althaf1088** [comment]
Hi @kerenlahav ,

We use crossplane to create CRs and we use multiple subaccounts in same cluster. So below is the current CR which works


```apiVersion: services.cloud.sap.com/v1
kind: ServiceInstance
metadata:
  name: message-instance
  namespace: development
spec:
  serviceOfferingName: message-queuing
  servicePlanName: standard
  parameters:
    sourceIPs: 0.0.0.0/0
    resources:
      units: "100" 
```



Since Crossplane does not support creating CRs with `namespace` property ask is whether it can accommodated like below



```apiVersion: services.cloud.sap.com/v1
kind: ServiceInstance
metadata:
  name: message-instance
spec:
  namespace: development 
  serviceOfferingName: message-queuing
  servicePlanName: standard
  parameters:
    sourceIPs: 0.0.0.0/0
    resources:
      units: "100"
```

**Comment by kerenlahav** [comment]
The example you specified actually means that a CR in namespace "default" should be treated like it was created in namespace "development", this contradicts the kubernetes/operator "contract".

You can have CRs for multiple subaccounts in one namespace by specifieng the secret name you want the operator to use:
apiVersion: services.cloud.sap.com/v1
kind: ServiceInstance
metadata:
  name: sample-instance-1
spec:
  serviceOfferingName: service-manager
  servicePlanName: subaccount-audit
  btpAccessCredentialsSecret: subaccount1

each secret will contain credentials for a different subaccount.
note that all the referenced secrets must be located in the same namespace as the CRs.

**Comment by althaf1088** [comment]
> The example you specified actually means that a CR in namespace "default" should be treated like it was created in namespace "development", this contradicts the kubernetes/operator "contract".
> 
> You can have CRs for multiple subaccounts in one namespace by specifieng the secret name you want the operator to use, using the **btpAccessCredentialsSecret** property:
> 
> ```
> apiVersion: services.cloud.sap.com/v1
> kind: ServiceInstance
> metadata:
>   name: sample-instance-1
> spec:
>   serviceOfferingName: service-manager
>   servicePlanName: subaccount-audit
>   btpAccessCredentialsSecret: subaccount1
> ```
> 
> each secret will contain credentials for a different subaccount. note that all the referenced secrets must be located in the same namespace as the CRs.

ok will try referring the secret directly and will update

**Comment by althaf1088** [comment]
Hi @kerenlahav 
I tried the above and was able to create serviceinstance referring the `btpAccessCredentialsSecret` only thing is it was expecting in `sap-btp-service-operator` namespace. 
```
Searching for secret name sap-btp-service-operator-1 in namespace sap-btp-service-operator
```

But looks like we still cannot use it in Crossplane composition because the CRD is `namespaced` scope. 
![Screenshot 2024-10-24 at 12 05 20 PM](https://github.com/user-attachments/assets/d9152741-0842-41e3-9ee9-71b987745e30)
 
As mentioned [here](https://github.com/crossplane/crossplane/issues/1730)

So even if i leave the namespace empty and use `btpAccessCredentialsSecret` still due to crossplane limitation , i get the below error 

```
an empty namespace may not be set when a resource name is provided
```

**Comment by kerenlahav** [comment]
about the btpAccessCredentialsSecret, you are right - it should be located in the management namespace as documented in the [read me](https://github.com/SAP/sap-btp-service-operator?tab=readme-ov-file#working-with-multiple-subaccounts)

When using kubectl, if namespace is not provided it defaults the "default" namespace, i'm not familiar with crossplane but according to the error you provided it does not seem to act the same, if namespaced resources are not supported than what you are looking for is a cluster resource which is not supported, you can raise a feature request [here](https://sap.sharepoint.com/sites/201434/SitePages/BTP-Cloud-Fundamental-Services-requirements-process.aspx?xsdata=MDV8MDJ8fGZjOGRmMzYwNjJkNjQyNzAxM2E0MDhkYzgwN2IwOWU5fDQyZjc2NzZjZjQ1NTQyM2M4MmY2ZGMyZDk5NzkxYWY3fDB8MHw2Mzg1MjY1MTMxMTUzNzA0MDR8VW5rbm93bnxWR1ZoYlhOVFpXTjFjbWwwZVZObGNuWnBZMlY4ZXlKV0lqb2lNQzR3TGpBd01EQWlMQ0pRSWpvaVYybHVNeklpTENKQlRpSTZJazkwYUdWeUlpd2lWMVFpT2pFeGZRPT18MXxMMk5vWVhSekx6RTVPakF6WWpBM09HTXhMVGd4TmpVdE5ERTVOUzA0WW1GakxUZGlNemhrTkRGaFpqYzFZMTloTVRkbVptVXdPUzAzT1ROakxUUTJZekF0WWpBellpMWxNbU0wTXpoa09UQmxaak5BZFc1eExtZGliQzV6Y0dGalpYTXZiV1Z6YzJGblpYTXZNVGN4TnpBMU5EVXhNVEF3TVE9PXxlYWE1ODI0ZDBmNWE0ZmVkYjE1ZTA4ZGM4MDdiMDllNnw3MDBmZjlkOGY5OGY0ZjdhYTExM2VjZTExMjVlYzFjNQ%3D%3D&sdata=Y2lCbnovc1N4TGhBbVNnUllIUFBMUS9tclFjeUNiSi9zSkMydndHMllRYz0%3D&ovuser=42f7676c-f455-423c-82f6-dc2d99791af7%2Ckeren.lahav%40sap.com&OR=Teams-HL&CT=1730004280520&clickparams=eyJBcHBOYW1lIjoiVGVhbXMtRGVza3RvcCIsIkFwcFZlcnNpb24iOiI1MC8yNDA5MDEwMTQyMyIsIkhhc0ZlZGVyYXRlZFVzZXIiOmZhbHNlfQ%3D%3D&SafelinksUrl=https%3A%2F%2Fsap.sharepoint.com%2Fsites%2F201434%2FSitePages%2FBTP-Cloud-Fundamental-Services-requirements-process.aspx) and it will be examined

**Comment by althaf1088** [comment]
Thanks. Yes to support crossplane composition , we will need a clusterscoped resource. Will raise a feature request. Thanks for your help
