### ISSUE TITLE
Orphaning a resource

### ISSUE THREAD

**Issue by jaylevin** [SAP/sap-btp-service-operator#474]
Is there a standard way we can orphan a resource with this operator? We want to transfer the control of our bindings and instances currently managed by BTP Operator in one cluster and move them to another cluster.

One way I was thinking is to just set the desired replicas for the operator deployment to 0, then force delete the CR from the cluster. This should work, but I wanted to know if there was any smoother way to do it (perhaps by using a `paused` annotation).

Thanks.

**Comment by kerenlahav** [comment]
There is no feature to move resources between clusters, you can use the recovery feature to acheive it.
Note that you can "move" a resource between physical clusters but not logical clusters (cluster id for resource cannot be changed, it is part of its context).

About the way you proposed, it will not work- you will not be able to delete the resource if the operator is down (the webhook call will fail).

What you can do is install the operator with the same cluster id and recover the instances in the new cluster (NOTE - if the CRs and cluster id are not identical the recovery will not work and a new resource will be created).
To delete the CR in the original cluster remove the finalizer and after the finalizer is removed delete the resource.
Please test it on one of the resources to verify the process.
