### ISSUE TITLE
Feature request: Secret rotation

### ISSUE THREAD

**Issue by thonacker** [SAP/sap-btp-service-operator#479]
Hi colleagues,

we found this feature: https://sap.github.io/cf-service-operator/docs/usage/servicebinding/ and thought about a rotation.
Looking at the BTP operator something similar would be great for Cloud Foundry: https://github.com/SAP/sap-btp-service-operator?tab=readme-ov-file#example

`apiVersion: services.cloud.sap.com/v1
kind: ServiceBinding
metadata:
  name: sample-binding
spec:
  serviceInstanceName: sample-instance
  credentialsRotationPolicy:
    enabled: true
    rotatedBindingTTL: 48h
    rotationFrequency: 600h`

I've talked to Christoph Barbian and he mentioned to do this in SPEC instead of using annotations.

Thank you and best regards
Tobias

**Comment by I065450** [comment]
Sorry, I didn't' understand the issue.
What do you need from us?

**Comment by sasg** [comment]
Sorry, this can be closed. Was wrongly created here.
