### ISSUE TITLE
Service Instance comes to a dead end when it is in the "deleted failed" status

### ISSUE THREAD

**Issue by madgrape** [SAP/sap-btp-service-operator#480]
Hi, colleagues,

I have been troubled by an issue for a long time. It occurs when DevOps deletes (sometimes by mistake) a service instance with active subscriptions, causing it to become a 'deleted failed' status. Then, we can do nothing but a complete unsub and purge.

Considering the error message shows the deletion has failed, the operation is blocked by active subscriptions, which means the deletion is not exec. So is it possible that a new update operation on the instance could reset the status and make the service instance back to active and usable again? Just the same as the "update failed" status does.

In some cases, we just do not want to have a purging but recovering.

**Comment by I065450** [comment]
Hi @madgrape 

Kubernetes doesn’t support an undo function for actions. 
To prevent similar cases in the future, you can add the annotation "services.cloud.sap.com/preventDeletion".
[documentation here](https://github.com/SAP/sap-btp-service-operator?tab=readme-ov-file#annotations).

Regards,
Naama

**Comment by madgrape** [comment]
Great, it is a preventative solution that works, thanks Naama. :)
