### ISSUE TITLE
Feature request: Add option for custom annotations

### ISSUE THREAD

**Issue by gi02sap** [SAP/sap-btp-service-operator#481]
Hi colleagues,

I am using the btp-operator in a setup where it (among other microservices) is deployed via ArgoCD. 
The parameters I use in the secret are imported from Hashicorp Vault via the ArgoCD Vault Plugin. Its' functionality relies on a certain annotation of the secret template and the current version of the secret doesn't provide the option to add this annotation:
https://argocd-vault-plugin.readthedocs.io/en/stable/howitworks/

With few simple changes of the secret template and the values file we can add the option for custom annotations.

**Comment by kerenlahav** [comment]
Hi @gi02sap 
please provide the tempalte with the required changes and we'll review it.
Thanks!

**Comment by gi02sap** [comment]
Hi @kerenlahav, 
Can you share any information whether the change will be included and when eventually?

**Comment by kerenlahav** [comment]
https://github.com/SAP/sap-btp-service-operator/pull/496
will be released next week
