### ISSUE TITLE
What are some ways to find the cluster ID?

### ISSUE THREAD

**Issue by nikoChen-I755695** [SAP/sap-btp-service-operator#484]
- **Background:** 
   I am currently following the instructions in the README.md to attempt **resource migration**, where the **cluster ID** is a crucial parameter in the migration process.

- **Problem description:**
At the third point in the "Verify" section of this document(https://github.com/SAP/sap-btp-service-operator/pull/466/files), two IDs are mentioned: **the cluster ID in the Kubernetes cluster** and **the ID associated with the SAP BTP service instance**. But how can I **obtain these two IDs?** The document is a bit vague, and I don't fully understand it.

**Comment by kerenlahav** [comment]
instance's cluster id is visibile in the cockpit or when getting instance details with btpcli.
the cluster id of the cluster is defined in a configmap named sap-btp-operator-config.
