### ISSUE TITLE
Secrets for a ServiceBinding are not recreated when deleted manually

### ISSUE THREAD

**Issue by markusbalsam** [SAP/sap-btp-service-operator#488]
I have observed that `Secrets` that have been created for a `ServiceBinding` aren't recreated when they're deleted manually. Looking at the controller code, `Secrets` seem to be created/updated only when the `ServiceBinding` has changed i.e., its observed generation is not the latest generation:

See [servicebinding_controller.go](https://github.com/SAP/sap-btp-service-operator/blob/main/controllers/servicebinding_controller.go#L141):

```go
if serviceBinding.Status.BindingID != "" && condition != nil && condition.ObservedGeneration != serviceBinding.Generation {
	err := r.updateSecret(ctx, serviceBinding, serviceInstance, log)
	if err != nil {
		return r.handleSecretError(ctx, smClientTypes.UPDATE, err, serviceBinding)
	}
	err = utils.UpdateStatus(ctx, r.Client, serviceBinding)
	if err != nil {
		return r.handleSecretError(ctx, smClientTypes.UPDATE, err, serviceBinding)
	}
}
```

I would expect that the `ServiceBinding` controller observes the `Secrets` for a binding and (re)creates them if they don't exist, like other controllers do (e.g., external-secrets, [see](https://github.com/external-secrets/external-secrets/blob/main/pkg/controllers/externalsecret/externalsecret_controller.go#L275)).

As far as I can see, the only mitigation for a deleted `Secret` is to delete and re-create the `ServiceBinding`.

As a side note, when a Secret is created using a template, the `managed-by-sap-btp-operator` label is set, but the `binding` annotation is not. This doesn't have any obvious impact on functionality but is at least inconsistent.

**Comment by kerenlahav** [comment]
The secret should be recreated, handle here https://github.com/SAP/sap-btp-service-operator/blob/b43ad4a82ef66ce455d0c51a156645270ff824bc/controllers/servicebinding_controller.go#L170-L169
The secret should be created eventually (during full reconcile), if it is not working as expected please attach the relevant operator's log and the binding's yaml

The annotation has no functional meaning, but i agree it should be consistent so we'll add it.
