### ISSUE TITLE
Service Binding fails for auditlog service instance

### ISSUE THREAD

**Issue by lholthof** [SAP/sap-btp-service-operator#490]
We tried to update an auditlog service instance which does not seem to be possible. The update failed with message:
"BrokerError:, Status: 400, Description: Updating service is currently not supported operation. Please create a new service with the desired updates and bind to it"
![image](https://github.com/user-attachments/assets/d09ce13b-ae8a-4ada-8186-0e6a65bbf359)

Now we are in a stuck situation, as there is no operation for us to mitigate the update failed state. As a follow-up issue we are unable to create new service bindings for this existing auditlog service instance.
![image](https://github.com/user-attachments/assets/f6f90c79-5d0a-47fb-aac3-5a72f4707bf7)

In Kyma a found in BTP Operator logs:
`2024-12-12T10:37:30Z INFO controllers.ServiceBinding Service instance with k8s name dsi-auditlog is not ready for binding yet {"servicebinding": {"name":"dsi-auditlog","namespace":"s-management"}, "correlation_id": "2152d7d7-32e2-4579-b92a-86cc1b86d107", "dsi-auditlog": "s-management"}
2024-12-12T10:37:30Z INFO controllers.ServiceBinding setting inProgress conditions: reason: CreateInProgress, message:creation in progress, waiting for service instance 'dsi-auditlog' to be ready, generation: 1 {"servicebinding": {"name":"dsi-auditlog","namespace":"s-management"}, "correlation_id": "2152d7d7-32e2-4579-b92a-86cc1b86d107", "dsi-auditlog": "s-management"}`

BTP Operator does not seem to forward the binding request at all because of the service instance update failed situation. As the instance is existing, I do not get the reason for this.

How to move on?

**Comment by kerenlahav** [comment]
This is a bug, will be fixed in the next release

**Comment by lholthof** [comment]
What is the expected schedule to receive this in EU12 Canary / EU10 Factory?

**Comment by kerenlahav** [comment]
This is a bug in the operator itself, we'll release a new version by EOW

**Comment by kerenlahav** [comment]
[PR](https://github.com/SAP/sap-btp-service-operator/pull/492) was merged, will be released on Sunday

**Comment by kerenlahav** [comment]
https://github.com/SAP/sap-btp-service-operator/releases/tag/v0.7.0
