### ISSUE TITLE
Hana Schema ServiceBinding creation fails because of 'no procedure with name UPDATE_USER_IDENTITY'

### ISSUE THREAD

**Issue by mdudushka** [SAP/sap-btp-service-operator#491]
Hello,

We have a Hana Cloud DB(hana-cloud-tools in BTP)  and a Kyma cluster. We are trying to deploy an app to Kyma that utilizes a service binding for Hana Schema but the creation of the service instance fails because of an error in the database.

Error: 

```
ServiceBinding create failed: Fail to add x509 identify to the user USR_<redacted>, because of: SAP DBTech JDBC: [328]: invalid name of function or procedure: no procedure with name UPDATE_USER_IDENTITY
```

We updated the Hana Cloud version but that didn't solve the issue.

For more context:
We have an automated Jenkins pipeline that deploys an app to Kyma and runs certain tests. The app in particular uses hana schema service instance. The service instance is created successfully but the service binding creation fails.

Any idea how to solve this issue?

**Comment by kerenlahav** [comment]
Hi @mdudushka 
The error is returned from the Hana broker, you need to check with them.
Thanks

**Comment by mdudushka** [comment]
Hi, The hana broker colleagues fixed the service binding creation. 

But now when the service binding is created the user field is empty. 

![Image](https://github.com/user-attachments/assets/dde471f4-5635-4a92-a9ba-ee614450a739)


Any idea why that is?

**Comment by kerenlahav** [comment]
the operator is not responsible for the credentials content and does not manipulates it, any issues with the credentials should be forwarded to the broker's team
