### ISSUE TITLE
Service binding could not be deleted

### ISSUE THREAD

**Issue by dileep-rk** [SAP/sap-btp-service-operator#493]
Hello,

While trying to delete a namespace with all its resources, the namespace deletion is stuck in `terminating` state, due to one of the service bindings is not getting deleted. I checked the respective binding, only the secret is deleted but not the binding. 

Now the respective service instance and other dependent service instances are also not getting deleted.

We are not able to create binding-secret also as it is complaining that `secrets "dsi-test-app-acfun001-imagepullsecret" is forbidden: unable to create new content in namespace s-test-app because it is being terminated`

We need help in clearing all resources within this namespace and also deleting this namespace.
Any help here would be greatly appreciated!

Thanks,
Dileep

**Comment by kerenlahav** [comment]
Hi @dileep-rk 
What is the status of the binding that is stuck in deletion? does it have any error?
Thanks

**Comment by dileep-rk** [comment]
Hi @kerenlahav,
It is having a 401 unauthorized error and it is in delete failed status.
I think since the secret is not present, it is not able to present credentials while trying to delete the bindings.
Thanks,
Dileep

**Comment by kerenlahav** [comment]
can you create the required secret in the management namespace?
https://github.com/SAP/sap-btp-service-operator?tab=readme-ov-file#working-with-multiple-subaccounts

**Comment by dileep-rk** [comment]
Hi @kerenlahav,
Do we need to create a dedicated namespace `management_namespace` and then create secret within this new namespace?
But, how can we link this secret to the failed service binding in the our terminating namespace `s-test-app`?
Thanks,
Dileep

**Comment by kerenlahav** [comment]
seems like you are using the default secret, the defualt managment namespace is "sap-btp-operator", try to create the secret with the relevant credentials in the management namespace and name it "sap-btp-service-operator"
restart the operator and see if the binding is deleted.

**Comment by dileep-rk** [comment]
Ok, do I need to restart the operator `sap-btp-operator-controller-manager` which is there in the `kyma-system` namespace?

**Comment by kerenlahav** [comment]
i didnt know it is kyma environment, i'm not sure what is the management namespace in that case, you can check it in the configmap named "sap-btp-operator-config".
after secret is created you should restart the btp operator pod

**Comment by kerenlahav** [comment]
any comments or issue can be closed?
