### ISSUE TITLE
ServiceBinding creation fails

### ISSUE THREAD

**Issue by wozniakjan** [SAP/sap-btp-service-operator#50]
When creating `ServiceBinding` for a `ServiceInstance` created by the operator, it frequently fails in my case.

```
$ k get serviceinstance
NAME                  OFFERING       PLAN      STATUS    READY   AGE
my-service-instance   auditlog-api   default   Created   True    2m48s
```
```
$ k get serviceinstance my-service-instance -o json | jq '.status.instanceID'
"71215544-0588-4458-af27-7c5d1a621815"
```
```
$ k get servicebinding
NAME         INSTANCE              STATUS         READY   AGE
my-binding   my-service-instance   CreateFailed   False   71s
```
```
$ k get servicebinding my-binding -o json | jq '.status.conditions[0].message'
"ServiceBinding create failed: request POST https://service-manager.cfapps.sap.hana.ondemand.com/v1/service_bindings failed: StatusCode: 409 Body: {\"error\":\"Conflict\",\"description\":\"binding with same name exists for instance with id 71215544-0588-4458-af27-7c5d1a621815\"}
```

Both service instance as well as binding get created and are visible in BTP Cockpit, but I suspect that the controller may be faster than the k8s cache update and potentially puts itself in a race condition in

https://github.com/SAP/sap-btp-service-operator/blob/9ed414590ffa9d8bcfd3c13ca4f00f79f9fcc2eb/controllers/servicebinding_controller.go#L178-L195

**Comment by kerenlahav** [comment]
Hi @wozniakjan 
I was not able to reproduce the issue with the latest version (0.1.8) of the operator, which version are you using?
Can you please share the operator's manager log?

**Comment by wozniakjan** [comment]
> Can you please share the operator's manager log?

sure thing, attaching the logs for the issue described here, I think it really might be a race condition when the controller during subsequent reconcile uses stale k8s cache. I also executed the following command to watch for any changes on the `ServiceBinding` and you can see that the version of SB before failure succeeded.
```
$ kubectl get servicebinding -o yaml -w > sb.watch.yaml.log
```

**watch:** [sb.watch.yaml.log](https://github.com/SAP/sap-btp-service-operator/files/6616057/sb.watch.yaml.log)
**controller logs:** [service_binding_failure.log](https://github.com/SAP/sap-btp-service-operator/files/6616049/service_binding_failure.log)

> I was not able to reproduce the issue with the latest version (0.1.8)
also using 0.1.8

```
$ k get po -o json -nsap-btp-operator | jq '.items[].spec.containers[].image'
"gcr.io/kubebuilder/kube-rbac-proxy:v0.5.0"
"ghcr.io/sap/sap-btp-service-operator/controller:v0.1.8"
```

It might be also worth noting that similar issue happens to me with much smaller frequency for `ServiceInstance`.

**Comment by wozniakjan** [comment]
During a debugging session with @kerenlahav, she discovered it is no issue when using correct plan `service-operator-access` for service manager, this issue only exists when using `subaccount-admin` plan because the instance context is different and btp-operator is unable to fetch the right instance from SM cache.
