### ISSUE TITLE
Install instructions miss CRD installation

### ISSUE THREAD

**Issue by wiegandf** [SAP/sap-btp-service-operator#52]
When following the install instructions from https://github.com/SAP/sap-btp-service-operator#setup, the operator fails to start because of missing CRDs:

```
2021-06-09T07:40:30.113Z	ERROR	controller-runtime.source	if kind is a CRD, it should be installed before calling Start	{"kind": "ServiceInstance.services.cloud.sap.com", "error": "no matches for kind \"ServiceInstance\" in version \"services.cloud.sap.com/v1alpha1\""}
github.com/go-logr/zapr.(*zapLogger).Error
	/go/pkg/mod/github.com/go-logr/zapr@v0.2.0/zapr.go:132
sigs.k8s.io/controller-runtime/pkg/source.(*Kind).Start
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.7.0/pkg/source/source.go:117
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.7.0/pkg/internal/controller/controller.go:159
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.7.0/pkg/internal/controller/controller.go:205
sigs.k8s.io/controller-runtime/pkg/manager.(*controllerManager).startRunnable.func1
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.7.0/pkg/manager/internal.go:691
2021-06-09T07:40:30.113Z	INFO	controller-runtime.webhook	shutting down webhook server
2021-06-09T07:40:34.063Z	ERROR	controller-runtime.source	if kind is a CRD, it should be installed before calling Start	{"kind": "ServiceBinding.services.cloud.sap.com", "error": "no matches for kind \"ServiceBinding\" in version \"services.cloud.sap.com/v1alpha1\""}
github.com/go-logr/zapr.(*zapLogger).Error
	/go/pkg/mod/github.com/go-logr/zapr@v0.2.0/zapr.go:132
sigs.k8s.io/controller-runtime/pkg/source.(*Kind).Start
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.7.0/pkg/source/source.go:117
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.7.0/pkg/internal/controller/controller.go:159
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.7.0/pkg/internal/controller/controller.go:205
sigs.k8s.io/controller-runtime/pkg/manager.(*controllerManager).startRunnable.func1
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.7.0/pkg/manager/internal.go:691
2021-06-09T07:40:34.063Z	ERROR	setup	problem running manager	{"error": "no matches for kind \"ServiceInstance\" in version \"services.cloud.sap.com/v1alpha1\""}
github.com/go-logr/zapr.(*zapLogger).Error
	/go/pkg/mod/github.com/go-logr/zapr@v0.2.0/zapr.go:132
main.main
	/workspace/main.go:122
runtime.main
	/usr/local/go/src/runtime/proc.go:203
```

**Comment by kerenlahav** [comment]
Hi, the CRDs are part of the helm charts (sap-operator.yaml) and should be deployed as part of the helm.
Have you encountered any error in the helm command?
helm upgrade --install sap-btp-operator https://github.com/SAP/sap-btp-service-operator/releases/download/<release>/sap-btp-operator-<release>.tgz \
    --create-namespace \
    --namespace=sap-btp-operator \
    --set manager.secret.clientid=<clientid> \
    --set manager.secret.clientsecret=<clientsecret> \
    --set manager.secret.url=<sm_url> \
    --set manager.secret.tokenurl=<url>

**Comment by wiegandf** [comment]
I was using https://github.com/SAP/sap-btp-service-operator/tree/main/sapbtp-operator-charts where this file is not included. 

I didn't see that you're publishing a different artifact. The instructions probably work then, but we should make the crd not part of the template folder: https://helm.sh/docs/chart_best_practices/custom_resource_definitions/#install-a-crd-declaration-before-using-the-resource

Maybe we could add the crds into the crds folder and allow users to opt into the install. This way, it's clear where to find the crds and users can decide whether to install via helm chart or separately.

**Comment by kerenlahav** [comment]
The CRDs can be found in /config/crd/bases
This chart is generated with the command "make helm-charts" which uses "kustomize" to build it

**Comment by pavelmaliy** [comment]
The CRDs can be found in the release or like @kerenlahav mentioned with make helm-charts command they'll be generated
