### ISSUE TITLE
Restrict permissions to selected namespaces

### ISSUE THREAD

**Issue by wiegandf** [SAP/sap-btp-service-operator#53]
Currently, the sap-btp-operator requires a lot of cluster-wide permissions (https://github.com/SAP/sap-btp-service-operator/blob/main/config/rbac/role.yaml).

We should narrow this down to the namespaces that the sap-btp-operator is watching.

**Comment by pavelmaliy** [comment]
The sap-btp-operator watches serviceinstances, servicebindings and secrets on all consumer namespaces which means all cluster.
Am I missing something?
