### ISSUE TITLE
multi service-manager with different BTP subaccount in one cluster

### ISSUE THREAD

**Issue by madgrape** [SAP/sap-btp-service-operator#77]
For the service catalog, we can install service-broker-proxy to achieve different namespaces mapping to different BTP subaccounts, which means, In one k8s cluster, we can provision BTP service instance for each BTP subaccount in different namespace.

To migrate btp-service-operator from the service catalog, how can I achieve this?
It seems that the clientid & clientSecret is provided during the installation of the btp operator.

**Comment by pavelmaliy** [comment]
hi please refer this issue:
https://github.com/SAP/sap-btp-service-operator/issues/67
