### ISSUE TITLE
Service Plan Information Missing in Kubernetes Secrets

### ISSUE THREAD

**Issue by MatKuhr** [SAP/sap-btp-service-operator#78]
Hi colleagues,

we noticed that upon creating a service binding (e.g. for XSUAA, IAS or Destination Service) the Service Operator "only" provides the credentials as Kubernetes secret.

However, some existing libraries and applications rely on other information that is usually available in the service binding. For example, the [Java Security Library](https://github.com/SAP/cloud-security-xsuaa-integration/) requires the service `plan` to be available for IAS or XSUAA bindings. Other services may provide other information outside of the service credentials, e.g. different endpoints for read/write, settings etc.

**Q:** Will the Service Operator provision such values in the future? If not, how should applications obtain the required information?

Thanks in advance!

**Comment by pbusko** [comment]
Hi @MatKuhr,

We have a similar problem with the `tags` information being unavailable for the proper `VCAP_SERVICES` env variables replication, so we created a proposal #80 to add `tags` key as a part of the secret.
I assume that the `plan` information could be handled in the similar way (i.e. `plan` key in the ServiceBinding secret).

**Comment by pavelmaliy** [comment]
@MatKuhr @pbusko 
we will provide a fix for that soon and all additional information will be on the secret.

@pbusko please close the PR as tags will be also available on the secret.
BTW query by catalog name can return multiple results because of subaccount scoped brokers and the tags could be wrong in your PR.

Thanks for your input.

**Comment by pavelmaliy** [comment]
please use release v0.1.12

**Comment by MatKuhr** [comment]
Thanks a lot for the quick response! My colleague @cschubertcs tried it out and it worked, the information is now available. Highly appreciated! We'll build on that and get back to you in case we have more feedback / questions.
