### ISSUE TITLE
Service Operator "Flattens" Nested Lists

### ISSUE THREAD

**Issue by MatKuhr** [SAP/sap-btp-service-operator#79]
Hi colleagues,

we noticed that if a service binding (e.g. identity service) has a property that is an array (e.g. `domains`), the property will be "flattened" into a single file.

E.g. Identity Service binding on CF:
```json
"credentials": {
            .....
            "domains": [
                "accounts400.ondemand.com"
             ]
}
```

on K8s we have a file `domains` containing:
```
["accounts400.ondemand.com"]
```

This poses a problem. Because in the “flattened” version applications need to "know" which fields are arrays. An application can’t just assume any value wrapped in `[` … `]` will be an array, it might also just be part of the value. E.g. a client secret.

For applications, this is at least inconvenient. For libraries & tools, that support various services, it's a slightly bigger problem. Do you think this could be improved in the future?

Kind regards,
Matthias

**Comment by MatKuhr** [comment]
One additional point: The same problem is also relevant for nested JSON objects. 

I don't know how that is handled at the moment, but I would guess:

```
"credentials": {
            .....
            "some-nested-object": {
                  "key": "val"
             }
} 
```

would result in a file `some-nested-object` containing:
```
{"key": "val"}
```

Again, with the same problem that we have in the list case.

**Comment by MatKuhr** [comment]
@jkbschmid was so kind to point me towards this option: https://github.com/SAP/sap-btp-service-operator/pull/62

We'll try that out as well as a workaround. Still, guidance on a long-term solution would be great

**Comment by loewenstein** [comment]
@MatKuhr is this solved via https://github.com/SAP/sap-btp-service-operator/pull/62 already? It is now possible to get the `credentials` structure as a whole in a single Secret key.
