### ISSUE TITLE
Plans for a Client Library?

### ISSUE THREAD

**Issue by cschubertcs** [SAP/sap-btp-service-operator#83]
Hi!

I'm part of the SAP Cloud SDK (Java) team and we are currently working on reading service bindings from K8S secrets, coming from CF with the bindings stored in the `VCAP_SERVICES`.
After discussion with @nenaraab we were thinking, that it could make sense that the Service Operator provides a library to read secrets as service bindings, kind of similar to the `@sap/xsenv` library for JavaScript.

Rough requirements would be:
- Being able to read a service binding from ...
    - ... secrets created by the service operator
    - ... environment variables (e.g. `VCAP_SERVICES` either on CF or "emulated" on K8S)
- Easy to extend with different reading logic, e.g. in case the secrets were created in a different way than "usual"

Do you have, by any chance, such a client library on the roadmap?

**Comment by pavelmaliy** [comment]
Hi,
I am not sure what the library should do,
K8S secrets can be mount as volume on any path or used directly as env, there is no well defined structure like in CF with VCAP_SERVICES.
So there is no generic way to know how secret will be mounted and in which path.
Actually it is a Kubernetes way to get service credentials from secrets and it's up to application to "know" how to use them.
So I see no reason to become a 'CF' on kubernetes

**Comment by cschubertcs** [comment]
Yes, that makes sense. But we don't mean to read generic secrets into objects, but rather concrete service bindings.

My idea with this issue was more to support reading service bindings created by the service operator.
This means the client library could expect a certain way the secrets were created, maybe the default format the service operator uses.
That way consumers could call your library and handle the service binding typed in Java.
Maybe this could also be configurable, so that the application can provide information on the given/expected secret/mount format.

The icying on the cake would then be to also support reading them from `VCAP_SERVICES`, so that the library can be used on K8S and CF.

**Comment by pavelmaliy** [comment]
I understand,
Of course it is possible what you suggest to identify the service name by volume name (in case of volumes) or by some other convention, the real problem is that in CF the environment is created by cloudfoundry and well structured but in K8S its created by user (owner of deployment).
Also currently there is no way to identify regular secret and secret created by service binding.

Anyway I am not aware of such library in the roadmap.
