### ISSUE TITLE
Storing all binding properties in single property/file

### ISSUE THREAD

**Issue by cschubertcs** [SAP/sap-btp-service-operator#84]
Hi!

Kind of related to #83.
We are currently working on a feature to read service bindings from secrets created by the service operator.
For that we already create tickets #78 and #79.

This means that we right now would expect the secret to be created using the `secretKey` parameter, creating a single property with the `credentials` JSON as it's value.
The other properties (as added with #78) are then added in parallel to the single `secretKey` property.

This, however, might now lead to the issue, that those other properties could be "flattened" (so a list of entries is stored as a String `"["value1", "value2"]"`).
From an SDK point of view we cannot know whether this is now a list or an actual String property.

Therefore the proposel to have an option to just store all properties into a single property.
The format of this could be guided by the usual CF `VCAP_SERVICES`, but could also be something "new".

**Comment by pavelmaliy** [comment]
Hi,
I am not sure we have an issue with additional properties because its closed group of properties provided by the operator,
instance_guid <string>, 
instance_name <string>, 
plan <string>, 
label (service name) <string>,
tags <string[]>
do you see a problem here?

**Comment by cschubertcs** [comment]
Okay, if the options here are really fixed to the specified ones, then there is no problem at the moment.

Then there is basically just one point left: Reading multiple files is kind of annoying, here a single file would make our life easier. Also, we don't see a benefit in storing those information in a single file, rather "downsides", that updates are likely not happening atomically.

**Comment by pavelmaliy** [comment]
you can prepare your env whatever suits you like this:
```
apiVersion: v1

kind: Pod

metadata:

    name: mypod

spec:

    containers:

        - name: myapp

        image: ubuntu

        env:

           - name: USERNAME

           valueFrom:

               secretKeyRef:

                   name: mysecret

                   key: username

           - name: PASSWORD

           valueFrom:

               secretKeyRef:

                   name: mysecret

                   key: password

**Comment by cschubertcs** [comment]
Hm, that would just push the burden to the consumer of the Cloud SDK.
As we are not handling the deployment, but just need to adapt to a given deployment by our consumers we would like to make their life in setting up the right kind of secrets as easy as possible.
Then they would not need to bother with consuming the secrets to communicate with the bound service.

**Comment by pavelmaliy** [comment]
you can now store binding data in single secret key,
if you set property secretRootKey

**Comment by cschubertcs** [comment]
Thanks, that looks really nice!
We will have a look to support and recommend that way.
