### ISSUE TITLE
Usage of a values.yaml

### ISSUE THREAD

**Issue by tomfrenken** [SAP/sap-btp-service-operator#87]
Hey colleagues, 

since you are publishing the operator as a helm chart, I was wondering if you could provide support for a values yaml where it is either possible to reference a secret that contains the credentials and/or writing the credentials directly into the values.yaml (the former would probably be better).

**Comment by pavelmaliy** [comment]
Hi I don't understand what do you mean by "writing the credentials directly into the values.yaml"
you can pass to helm whatever values.yml  you like with --values flag

**Comment by tomfrenken** [comment]
Well, the current recommended approach to set the values according to the README is this:

```
helm upgrade --install sap-btp-operator https://github.com/SAP/sap-btp-service-operator/releases/download/<release>/sap-btp-operator-<release>.tgz \
    --create-namespace \
    --namespace=sap-btp-operator \
    --set manager.secret.clientid=<clientid> \
    --set manager.secret.clientsecret=<clientsecret> \
    --set manager.secret.url=<sm_url> \
    --set manager.secret.tokenurl=<url>
```

Instead of using the `--set` flag, would it also be possible to write a values.yaml that looks like this:

```
manager:
  secret:
     clientid: "some-id"
     clientsecret: "123"
     url: "someurl"
     tokenurl: "some_token_url"
```

Furthermore, would it be possible to use a secret from which the values are just taken?
For example, just specifying a secret in the values.yaml?

```
manager:
  secretRef: "my_secret_on_k8s"
```

**Comment by pavelmaliy** [comment]
you can do it like this:
helm upgrade --install sap-btp-operator https://github.com/SAP/sap-btp-service-operator/releases/download/<release>/sap-btp-operator-<release>.tgz \
    --create-namespace \
    --namespace=sap-btp-operator \
   --values=/path/to/yaml

**Comment by tomfrenken** [comment]
Ah I see, thanks for helping us out!

**Comment by rufreakde** [comment]
Hi @pavelmaliy ,

I know there is a solution to this issue but it also would be much simpler to allow a helmchart value for:
existingSecret 

As explained in detail here:
https://utkuozdemir.org/blog/argocd-helm-secrets/

This would improve the usability of this operator and solidify the operator pattern which is declarative based. Could you create a backlog for this or task or similar for tracking?

Best regards,
Rudolf
